### ISSUE TITLE
PEP authentication in postAction.js or updateAction.js

### ISSUE THREAD

**Issue by Secmotic** [telefonicaid/perseo-fe#110]
Hi,
As I can see in the architecture of Perseo, the CEP is able to retrieve a token. I am using a keystone as IdM (https://github.com/ging/fi-ware-idm).
In the moment of the alert launched, the Action is calling to the keystone with a "Trust" attribute.

I can not find any documentation about this, and I have been trying by inserting trusted entities in the IdM database without any success.

Any hints please?
Thank you

**Comment by dmoranj** [comment]
Perseo CEP was developed to work with an standard Keystone installation, using Telefonica I+D FIWARE-based components, and I'm afraid it has not been tested with Ging's IDM or PEP Proxy. You can take a peek on how we installed the Keystone for Telefonica I+D IoT Platform here:

https://github.com/telefonicaid/fiware-pep-steelskin/blob/master/keystoneInstallation.md 

The Trust tokens referred in the CEP documentation are part of Keystones role delegation mechanisms. You can find an introduction here (official documentation may be elusive):

http://techs.enovance.com/5858/role-delegation-in-keystone-trusts

The idea is for you to create a trust token to give a certain rule the role permissions of the token, so it will be able to pass through a PEP Proxy connected to that Keystone.

Hope it solves some of your doubts.

**Comment by fgalan** [comment]
Regarding how to use the trust token in Perseo, have a look to this piece of documentation: https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#update-attribute-action

> trust: optional, trust token for getting an access token from Auth Server which can be used to get to a Context Broker behind a PEP.

**Comment by crbrox** [comment]
No new inputs in the last 12 months. Closing
