### ISSUE TITLE
template as JSON list/object in HTTP Post action

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#111]
Current Perseo FE assumes that the `template` on a HTTP Post action is always a string:

```
 "action": {
        "type": "post",
        "template": "Meter ${Meter} has pression ${Pression}.",
        "parameters": {
            "url": "localhost:1111"
        }
    }
```

However, it could be interesting to generize and allow also `template` as JSON list and JSON object. The variable expansion for `${...}` should be done in any subelement of this JSON.

**Comment by crbrox** [comment]
superseded by  #144 (PR: #188)
