### ISSUE TITLE
Improve generic POST action

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/perseo-fe#144]
Allow to send any content-type and customize the header of the outgoing POST (right now only a string in JSON can be sent)

**Comment by fgalan** [comment]
Maybe the same system though for NGSIv2 (https://github.com/telefonicaid/fiware-orion/issues/2015) could be reused (partialy or fully) in this case.

**Comment by crbrox** [comment]
DM-1842

**Comment by fgalan** [comment]
Implemented by PR #188
