### ISSUE TITLE
perseo-fe should be case sensitive with servicePaths

### ISSUE THREAD

**Issue by anabelengp** [telefonicaid/perseo-fe#146]
Other fiware componentes, such as ContextBroker, allow specifying case sensitive servicePaths. This is, ContextBroker takes as different servicePaths this two examples: `\gardens` and `\Gardens`.

However, when Perseo sends an updateContext to CB with servicePath `\Gardens`, it always converts the servicePath to lowercase, so CB will take this servicePath `\gardens` as a different one.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/issues/147. Holding opened so @anabelengp could check it works before closing this issue definitively.

**Comment by fgalan** [comment]
It seems it works as expected, looking to code:

https://github.com/telefonicaid/perseo-fe/blob/1f3c70c94bccb50b74d9c2e827fa9ffb577f0491/lib/middleware/service.js#L34-L65

In particular:

```
req.service = service.toLowerCase(); 
```

Moreover, the following unit test is checking this functionality: https://github.com/telefonicaid/perseo-fe/blob/master/test/unit/service_middlewr_utest.js

Thus, we can close this (very old :) issue.
