### ISSUE TITLE
Saving rules with invalid EPL text (update)

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/perseo-fe#177]
When updating a rule, it is stored in BD before checking again that the EPL text is valid. So an invalid EPL can be saved and can cause the FE to refuse to start at the initial refreshing of rules, forcing manual removing of the offending rule/s

(develop + release 0.7.0 )

**Comment by fgalan** [comment]
Fixed by PR #175 (release/0.7.0) and #179 (develop).

**Comment by fgalan** [comment]
Also fixed in release/1.0.0 with PR https://github.com/telefonicaid/perseo-fe/pull/180
