### ISSUE TITLE
Wrong test in visual_rules_test

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/perseo-fe#178]
The test for PUTing a VR is using DeleteVR in some of the cases
https://github.com/telefonicaid/perseo-fe/blob/master/test/component/visualrules_test.js#L335
https://github.com/telefonicaid/perseo-fe/blob/master/test/component/visualrules_test.js#L347

**Comment by fgalan** [comment]
Closeable after merging PR https://github.com/telefonicaid/perseo-fe/pull/185 ?

**Comment by crbrox** [comment]
Correct, fixed by #185
