### ISSUE TITLE
Weird behavior of POST action

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/perseo-fe#191]
The `post`action performs and additional level of stringification of the template so the body of the request is a string in JSON which content is the result of substitution (and the content-type is always 'application/json')
For example 
with ${X} as template and X with a value of 3 it sends
"3"
as body instead of 
3

or
with X is ${X} as template is sends
"X is 3"
(content-type: application/json)
instead of 
X is 3 

A nested level of 'serialization' that makes inappropriate for calling external APIs

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/188
