### ISSUE TITLE
Allow rules to have more than one action

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/perseo-fe#197]
One rule will trigger several actions. This avoids repeating th rule just for executing different actions

**Comment by crbrox** [comment]
@iariasleon , for testing before closing it definitively

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/perseo-fe/issues/197

**Comment by iariasleon** [comment]
LGTM
https://pdihub.hi.inet/fiware/iotp-pqa/pull/546
