### ISSUE TITLE
When the json sent to Perseo is too long, the parsing fails

### ISSUE THREAD

**Issue by jcalderin** [telefonicaid/perseo-fe#24]
When the json sent to CEP is too long, the perseo-core fails parsing the json

```
{"error":"error post to http://10.95.82.36:8080/perseo-core/rules (Unterminated string at 2897 [character 2898 line 1])","data":null}
```

**Comment by fgalan** [comment]
In addition to a fix in the code to check JSON length and report an error, the "too long" should defined (and documented) as part of the resolution of this bug.

**Comment by crbrox** [comment]
Please move it to perseo-core ("where it belongs")

**Comment by fgalan** [comment]
Moved to perseo-core repo: https://github.com/telefonicaid/perseo-core/issues/6
