### ISSUE TITLE
[CONF] Support PERSEO_MONGO_HOST environment variable to use full endpoint

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/perseo-fe#243]
Support PERSEO_MONGO_HOST environment variable to use full endpoint
We need to configure perseo-fe setting this variable as following:
PERSEO_MONGO_HOST="host" -> Then listen to mongodb hostname/ip:27017
PERSEO_MONGO_HOST="host:port" -> Then listen to mongodb hostname/ip:port
PERSEO_MONGO_HOST="host1:port,host2:port,host3:port" -> Then listen to mongodb host1:port,host2:port,host3:port

References:
https://github.com/telefonicaid/perseo-fe/blob/master/documentation/configuration.md
https://github.com/telefonicaid/perseo-fe/blob/master/bin/perseo#L78
```
    if (process.env.PERSEO_MONGO_HOST) {
        config.mongo.url = 'mongodb://' + process.env.PERSEO_MONGO_HOST + ':27017/cep';
        config.orionDb.url = 'mongodb://' + process.env.PERSEO_MONGO_HOST + ':27017/orion';
}
```

**Comment by cesarjorgemartinez** [comment]
Info over mongodb drivers: http://mongodb.github.io/node-mongodb-native/2.2/upgrade-migration/main/
If use 2.2 then must be provided replicaset prefix (Its this case)
Other components is working because use 2.1 version (iota's)
Exam for iotas: When update mongodb drivers in https://github.com/telefonicaid/iotagent-node-lib/blob/master/package.json, to 2.2, then will be fail

**Comment by fgalan** [comment]
At the end, after discussion, we are going to use PERSEO_MONGO_ENDPOINT as env var, which conent is a MongoDB connections string, potenatially including the `replicaSet` option.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/247
