### ISSUE TITLE
Per-rule endpoint and from in SMS rules

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#269]
Currently, all the SMS rules use the same from tlf and SMPP (when `config.smpp` is used) or ACDC  (when `config.sms` is used) endpoint.

This issue is about moving that configuration from config.js to the rule information. That way, each rule would have its own from tlf and endpoint information.

There is a problem to take into account: the endpoint used for SMPP in a rule will not be valid for ACDC and viceversa. Than means that in a given situation, if the CEP runs with `config.sms` and has for instance a rule using the ACDC endpoint, then is restarted using `config.smpp` the rule is not going to work.

**Comment by AlvaroVega** [comment]
Not just rules should be modified. I've see:
- Modify actions (SMS and SMPP) to handle that endpoint instead of config endpoint
- Modify UI component to create rules (visualrules / portal)

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/518
