### ISSUE TITLE
error writing in log (no space left on device)

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/perseo-fe#27]
log message:
```
fs.js:539
  return binding.write(fd, buffer, offset, length, position);
                 ^
Error: ENOSPC, no space left on device
    at Object.fs.writeSync (fs.js:539:18)
    at SyncWriteStream.write (fs.js:1751:6)
    at logWrap (/opt/perseo/node_modules/fiware-node-logger/lib/fiware-node-logger.js:150:14)
    at process.<anonymous> (/opt/perseo/bin/perseo:10:12)
    at process.emit (events.js:95:17)
    at process._fatalException (node.js:272:26)
```
df -h
```
/dev/mapper/vg0-lv_var_log        504M  469M   11M  98% /var/log
```

**Comment by fgalan** [comment]
What should be the expected behaviour when there is no more space of disk to write the log? Disable the log and keep running (I think that CB does this)? To die?

**Comment by iariasleon** [comment]
CB when there is not more space, not write more in the log, and keep running. Perseo died and after does not start, showing above message.

**Comment by crbrox** [comment]
Are you sure is a requirement for all components in the platform to run without writing logs or start without space on disk?

**Comment by iariasleon** [comment]
I'm not sure on this component, we ask to product, but the error message should be an error message controlled, not an exception and append this behaviour in documentation.

**Comment by crbrox** [comment]
The error message is completely "controlled", https://github.com/telefonicaid/perseo-fe/blob/master/bin/perseo#L33
The stack trace is written intentionally, I think it contains information that can be useful. 
It's an exception of the log library, it can generate a quite few more and it's not practical or even posible to document all  and each one of the exceptions that external libraries can throw (I think Java components do not do that either .. )

**Comment by iariasleon** [comment]
LGTM
