### ISSUE TITLE
DELETE rules with id doesn't work

### ISSUE THREAD

**Issue by agaldemas** [telefonicaid/perseo-fe#270]
the deletion of a rule through the api does not work, whatever id is given in the request http://perseo-fe:9090/rules/{id}, with proper headers (service & servicepath), the answer content is : 
```
{
    "error": null,
    "data": [
        {
            "n": 0,
            "ok": 1
        },
        [
            {
                "code": 200,
                "body": "{}\n"
            },
            null
        ],
        null
    ]
}
```
and status 200
but the rule, if exists, is not deleted in the mongo database !

**Comment by agaldemas** [comment]
But it works by giving the rules name, but not with the rules id !
it can be acceptable, 
but it's not clear in the documentation (https://github.com/telefonicaid/perseo-fe/blob/master/documentation/api.md), it's written "DELETE | /rules/{id} | Delete rule with **name id**"

**Comment by fgalan** [comment]
Yes, the id of a rule is its name field. I understand the issue can be closed, so I'm doing so.

Thanks for the feedback!
