### ISSUE TITLE
[Deployment] What's the simplest way to demo perseo?

### ISSUE THREAD

**Issue by ledicjp** [telefonicaid/perseo-fe#271]
### Hello everyone,
I need to play around with perseo for one of my seminars and I've followed the deployment docs for perseo_core and perseo_fe but I just can't get perseo_fe to run, (using docker).

#### My procedure:
1. Started a mongo docker container ✅ 
2. Started an orion docker container ✅ 
3. Started a perseo_core docker container (which seems to work fine) ✅ 
`docker run -d --name perseo_core -h perseocore -p 8080:8080 telefonicaiot/perseo-core:latest -perseo_fe_url perseo:9090`
4. Trying to do the last step and start a perseo_fe container
`docker run -d -p 9090:9090 --name perseo_fe -h perseo --link perseo_core --link mongo --link orion -e "PERSEO_MONGO_HOST=mongo" -e "PERSEO_CORE_URL=http://perseocore:8080" -e "PERSEO_LOG_LEVEL=debug" -e "PERSEO_ORION_URL=http://orion:1026/v1/updateContext" telefonicaiot/perseo-fe:latest`
##### -> Fails without any error message every time...

I've tried different parameters already for my `docker run` commands, but when I `docker ps` only the processes for mongo, orion and perseo_core show up, the perseo_fe never even makes it to the process list. Maybe someone can find a mistake in my docker run commands.

I just need to run it locally for a day or two, alternatively an online demo of perseo would probably be enough for me as well, if there is one.

Thank you

**Comment by fgalan** [comment]
Have you checked perseo_fe logs? Maybe the can provide some useful information or hint about the problem.

**Comment by ledicjp** [comment]
Yeah good idea, I will check the logs and report, I just thought that someone more experienced can potentially see a flaw in my docker commands

**Comment by ledicjp** [comment]
Okay thanks for your help so far

**Comment by ledicjp** [comment]
I wanted to come back to post my solution:

Everything worked out of the box with **MongoDB 3.2**
Higher versions didn't work

**Comment by fgalan** [comment]
Great to know at the end finally worked!

I know of environments that use Perseo with MongoDB 3.4. But maybe there is some difference between them and yours, so in your case only works with 3.2... Anyway, if that version suffices your use case, then it's fine :)

**Comment by anmobor** [comment]
Hello, I am installing Perseo CEP from https://perseo.readthedocs.io/en/latest/admin/ and I would like to know if that restriction is still affecting the installation because I had already installed Mongo 3.6 previously to Perseo CEP. 
When I run Perceo I get this error: 
time=2019-05-06T15:14:19.419Z | lvl=ERROR | corr=n/a | trans=n/a | op=checkDB | comp=perseo-fe | msg=ensureIndex [object Object] not
authorized on cep to execute command { listIndexes: "rules", cursor: {}, $db: "cep" }

**Comment by fgalan** [comment]
@anmobor I think it would be better to ask for support to your problem using StackOverflow (https://stackoverflow.com). Could you please post there, please? Use "fiware-perseo" label.

Please add the link to the question to StackOverflow as a new comment to this issue once you do it. Thanks!

**Comment by anmobor** [comment]
I have asked for support to my problem using StackOverflow:
I set several questions if you could answer some of them I would really appreciate it, the questions are:
https://stackoverflow.com/questions/56057632/fiware-perseo-cep-is-not-sending-emails-i-cant-see-the-rules-in-mongo-but-when

https://stackoverflow.com/questions/56091838/perseo-front-end-is-showing-this-errors-in-the-logs-msg-missing-subservice-head

Thank you in advance
