### ISSUE TITLE
Missing TLS options in smtp config section

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/perseo-fe#272]
Missing TLS options in smtp config section

In https://github.com/telefonicaid/perseo-fe/blob/master/config.js, not use TLS options

See:
http://nodemailer.com/smtp/

**Comment by cesarjorgemartinez** [comment]
TLS options

    secure – if true the connection will use TLS when connecting to server. If false (the default) then TLS is used if server supports the STARTTLS extension. In most cases set this value to true if you are connecting to port 465. For port 587 or 25 keep it false
    tls – defines additional node.js TLSSocket options to be passed to the socket constructor, eg. {rejectUnauthorized: true}.
    ignoreTLS – if this is true and secure is false then TLS is not used even if the server supports STARTTLS extension
    requireTLS – if this is true and secure is false then Nodemailer tries to use STARTTLS even if the server does not advertise support for it. If the connection can not be encrypted then message is not sent

**Comment by fgalan** [comment]
Partically addressed (`tls` option) in PR https://github.com/telefonicaid/perseo-fe/pull/275.

`secure` is already implemented. `ignoreTLS` and `requireTLS` would be defered to a next PR

**Comment by AlvaroVega** [comment]
Now nodemailer dep has been updated recently.
Now each email rule support their own smtp configuration.
So we can close this issue.
