### ISSUE TITLE
add updateAction to updateAttribute card

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#278]
updateAction is fixed to APPEND.

To create a rule to trigger a command ```updateAction``` should be UPDATE instead of APPEND
https://github.com/telefonicaid/perseo-fe/blob/master/lib/models/updateAction.js#L135

A selector about updateAction is desirable

**Comment by fgalan** [comment]
Right now we have "update attribute action" (see https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md).

I suggest to add a new field to that rule parameters in order to select the actionType to use (either "UPDATE" or "APPEND"). The field name would be "actionType". Eg:

```json
"action":{
        "type":"update",
        "parameters":{
            "id":"${id}_mirror",
            "actionType": "UPDATE",
            "attributes": [
                {
                    "name":"abnormal",
                    "type":"boolean",
                    "value":"true"
                }
            ]
        }
    }
```

If ommited "actionType", then "APPEND" is use (to keep backward compatibility)

**Comment by mrutid** [comment]
Agree.

**Comment by fgalan** [comment]
Looking in the code this is the point in which actionType is set (https://github.com/telefonicaid/perseo-fe/blob/master/lib/models/updateAction.js#L135):

```
 updateAction: 'APPEND'
```

It seem that variable parameter are taken from a `options` object, so something like this could be used:

```
 updateAction: options.actionType
```

`options` is filled by the `buildUpdateOptions()` method, which uses `action` as parameter. I understand (although I'm not sure) that `action` comes from the rule stored in DB. It seems that Perseo processes action parameters in a blindly way, so if the rule was created with a `X` parameter, that parameter value willl be available inside `buildUpdateOptions()` as `action.parameters.X`. At least I haven't find any place declaring a fixed schema of parameters in the code.

Applying this to `actionType` parameters, it would be available as `action.parameter.actionType`.

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/280
