### ISSUE TITLE
Problem upgrading attribute 

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/perseo-fe#281]
Hello

I am testing the perseo-fe tool. 
The test environment I have created is the following:
I have created three entity  in service: city and sub-service: parking

[
    {
        "id": "parkingcity-02",
        "type": "parking",
        "parkingMax": {
            "type": "Number",
            "value": "100",
            "metadata": {}
        },
        "description": {
            "type": "Text",
            "value": " parking center 2",
            "metadata": {}
        },
        "freeParking": {
            "type": "Number",
            "value": "70",
            "metadata": {}
        }
    },
    {
        "id": "parkingcity-03",
        "type": "parking",
        "parkingMax": {
            "type": "Number",
            "value": "100",
            "metadata": {}
        },
        "description": {
            "type": "Text",
            "value": " parking center 3",
            "metadata": {}
        },
        "freeParking": {
            "type": "Number",
            "value": "30",
            "metadata": {}
        }
    },
    {
        "id": "parkingcity-04",
      "type": "parking",
        "parkingMax": {
            "type": "Number",
            "value": "100",
            "metadata": {}
        },
        "description": {
            "type": "Text",
            "value": " parking center 4",
            "metadata": {}
        },
        "freeParking": {
            "type": "Number",
            "value": "10",
            "metadata": {}
        }
    }
]
The rule is below:
{
   "name":"parking-rule",
   "text":"select *,\"parking-rule\" as ruleName from pattern [every ev=iotEvent(cast(cast(ev.freeParking?,String),int)>50 and type=\"parking\")]",
    "action":{
        "type":"update",
        "parameters":{
        	"type": "parking",
            "isPattern": "false",
            "id": "${id}",
            "attributes": [
                {
                    "name":"description",
                    "value":"Modify by rule",
                    "type":"Text"
                }
            ]
        }
    }   
}

The perseo log shows the notification but perseo-fe do not execute the rule when I modify the freeParking attribute to 80 in some entity.

**Comment by AlvaroVega** [comment]
Which version of perseo-fe are you using?

**Comment by AlvaroVega** [comment]
What about perseo subscription in context broker?

**Comment by amfgomez** [comment]
{
        "id": "5b911d33ab429ab2e7c675dc",
        "description": "subcription_test",
        "status": "active",
        "subject": {
            "entities": [
                {
                    "idPattern": "parkingcity-02",
                    "type": "parking"
                }
            ],
            "condition": {
                "attrs": [
                    "freeParking"
                ]
            }
        },
        "notification": {
            "timesSent": 41,
            "lastNotification": "2018-09-06T16:46:57.00Z",
            "attrs": [
                "parkingMax",
                "description",
                "freeParking"
            ],
            "attrsFormat": "legacy",
            "http": {
                "url": "http://172.17.0.9:9090/notices"
            },
            "lastFailure": "2018-09-06T16:43:30.00Z",
            "lastSuccess": "2018-09-06T16:46:57.00Z"
        }
    }

**Comment by amfgomez** [comment]
this subscription is activated and work, the perseo-fe log received the notifications.

**Comment by AlvaroVega** [comment]
Could please you start perseo with debug level logs  and provide us that logs?

**Comment by amfgomez** [comment]
time=2018-09-09T12:15:48.094Z | lvl=INFO | corr=15b7d5ee-b42a-11e8-a15f-0242ac110003; perseocep=10 | trans=ca53e54e-c63c-4a05-ad16-baac9acee236 | op=/notices | path=/notices | comp=perseo-fe | srv=malaga | subsrv=/aparcamiento | from=::ffff:172.17.0.3 | msg=incoming request {"method":"POST","url":"/notices","headers":{"user-agent":"orion/1.15.1 libcurl/7.29.0","host":"172.17.0.9:9090","fiware-service":"malaga","fiware-servicepath":"/aparcamiento","x-auth-token":"27a91e4e9d5340aea5394ebef81ef19f","accept":"application/json","content-length":"435","content-type":"application/json; charset=utf-8","fiware-correlator":"15b7d5ee-b42a-11e8-a15f-0242ac110003"},"body":{"subscriptionId":"5b911d33ab429ab2e7c675dc","originator":"localhost","contextResponses":[{"contextElement":{"type":"aparcamiento","isPattern":"false","id":"aparcamientoMalaga-02","attributes":[{"name":"aparcamientoMax","type":"Number","value":"100"},{"name":"descripcion","type":"Text","value":"Es el aparcamiento del centro 2"},{"name":"plazaslibres","type":"Number","value":"40"}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]},"subservice":"/aparcamiento","service":"malaga"}
time=2018-09-09T12:15:48.096Z | lvl=INFO | corr=15b7d5ee-b42a-11e8-a15f-0242ac110003; perseocep=10 | trans=ca53e54e-c63c-4a05-ad16-baac9acee236 | op=/notices | path=/notices | comp=perseo-fe | srv=malaga | subsrv=/aparcamiento | from=::ffff:172.17.0.3 | msg=making post to http://perseo_core:8080/perseo-core/events
time=2018-09-09T12:15:48.108Z | lvl=DEBUG | corr=15b7d5ee-b42a-11e8-a15f-0242ac110003; perseocep=10 | trans=ca53e54e-c63c-4a05-ad16-baac9acee236 | op=/notices | path=/notices | comp=perseo-fe | srv=malaga | subsrv=/aparcamiento | from=::ffff:172.17.0.3 | msg=post to http://perseo_core:8080/perseo-core/events returns {"code":200}
time=2018-09-09T12:15:48.108Z | lvl=INFO | corr=15b7d5ee-b42a-11e8-a15f-0242ac110003; perseocep=10 | trans=ca53e54e-c63c-4a05-ad16-baac9acee236 | op=/notices | path=/notices | comp=perseo-fe | srv=malaga | subsrv=/aparcamiento | from=::ffff:172.17.0.3 | msg=done post to http://perseo_core:8080/perseo-core/events
time=2018-09-09T12:15:48.109Z | lvl=INFO | corr=15b7d5ee-b42a-11e8-a15f-0242ac110003; perseocep=10 | trans=ca53e54e-c63c-4a05-ad16-baac9acee236 | op=/notices | path=/notices | comp=perseo-fe | srv=malaga | subsrv=/aparcamiento | from=::ffff:172.17.0.3 | msg=sending response: 200 {"error":null,"data":[{"code":200}]}
time=2018-09-09T12:15:48.110Z | lvl=DEBUG | corr=15b7d5ee-b42a-11e8-a15f-0242ac110003; perseocep=10 | trans=ca53e54e-c63c-4a05-ad16-baac9acee236 | op=/notices | path=/notices | comp=perseo-fe | srv=malaga | subsrv=/aparcamiento | from=::ffff:172.17.0.3 | msg=response-time: 19 statusCode: 200
time=2018-09-09T12:15:53.084Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE) {"ok":1}
time=2018-09-09T12:15:53.084Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE_ORION) {"ok":1}

**Comment by AlvaroVega** [comment]
Probably fixed by PR https://github.com/telefonicaid/perseo-fe/pull/282

**Comment by fgalan** [comment]
Which exact value did you use to set the action type? Please, include the request you used as a comment.

**Comment by amfgomez** [comment]
I always use type update but after your post, I have put action and it did not work

**Comment by AlvaroVega** [comment]
Did you tried with current master version?

**Comment by amfgomez** [comment]
I have to compile the new docker to test your solution.

**Comment by fgalan** [comment]
> I always use type update but after your post, I have put action and it did not work

Just to clarify... we have the action type (`"action": "update"`) but also the actionType as parameter of the update operation in CB (e.g. `"actionType": "UPDATE"`). Please have a look to documentation and example at https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#update-attribute-action which show how they are used.

**Comment by amfgomez** [comment]
This is my new rule based on documentation but it still doesn't work, it does not modify the content of the description field. 
{
   "name":"parking-rule2",
   "text":"select *,\"parking-rule2\" as ruleName from pattern [every ev=iotEvent(cast(cast(ev.plazaslibres?,String),int) > 50 and type=\"aparcamiento\")]",
    "action":{
    	"type":"update",
        "parameters":{
        	"id":"${id}",
            "attributes": [
                {
                	
                    "name":"descripcion",
                    "type":"Text",
                    "value":"Modificado por la regla"
                }
            ],
            "actionType": "UPDATE"
        }
    }   
}

**Comment by AlvaroVega** [comment]
Did you tried with actionType = APPEND ?

**Comment by amfgomez** [comment]
yes, the append or update attribute do not work

**Comment by AlvaroVega** [comment]
Both APPEND and UPDATE worked to me. Make sure you are using perseo-fe form master

**Comment by amfgomez** [comment]
yes, I am using the master branch.
1 I cloned the git in my pc
2 I modified the config.js file with my configuration 
3 I ran the docker build
--------- postman ------
4 I have created the rule
5 I updated the entity
6 I checked the description field of the entity. 
when I check the field, it contains the first description, it has not modified by the rule.

**Comment by AlvaroVega** [comment]
Could you try again? New updated were done.

**Comment by amfgomez** [comment]
Hello
I have used the new docker with the upgrades
The following lines are the pereseo-fe log after the upgrade entity file was executed in Postman.

time=2018-09-10T20:41:22.543Z | lvl=INFO | corr=e0e0cbd0-b539-11e8-a247-0242ac110003; perseocep=28 | trans=ab49e201-b502-443b-a234-d939c0518af2 | op=/notices | path=/notices | comp=perseo-fe | srv=city | subsrv=/parking | from=::ffff:172.17.0.3 | msg=incoming request {"method":"POST","url":"/notices","headers":{"user-agent":"orion/1.15.1 libcurl/7.29.0","host":"172.17.0.10:9090","fiware-service":"city","fiware-servicepath":"/parking","x-auth-token":"dd111b69be624ca4b9866cd792e7a47b","accept":"application/json","content-length":"431","content-type":"application/json; charset=utf-8","fiware-correlator":"e0e0cbd0-b539-11e8-a247-0242ac110003"},"body":{"subscriptionId":"5b96cc01f0fa37b4a4c3e7d9","originator":"localhost","contextResponses":[{"contextElement":{"type":"parking","isPattern":"false","id":"parkingcity-02","attributes":[{"name":"parkingMax","type":"Number","value":100},{"name":"description","type":"Text","value":"parking number 2"},{"name":"freeParking","type":"Number","value":60}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]},"subservice":"/parking","service":"city"}
time=2018-09-10T20:41:22.544Z | lvl=INFO | corr=e0e0cbd0-b539-11e8-a247-0242ac110003; perseocep=28 | trans=ab49e201-b502-443b-a234-d939c0518af2 | op=/notices | path=/notices | comp=perseo-fe | srv=city | subsrv=/parking | from=::ffff:172.17.0.3 | msg=making post to http://perseo_core:8080/perseo-core/events
time=2018-09-10T20:41:22.571Z | lvl=DEBUG | corr=e0e0cbd0-b539-11e8-a247-0242ac110003; perseocep=28 | trans=ab49e201-b502-443b-a234-d939c0518af2 | op=/notices | path=/notices | comp=perseo-fe | srv=city | subsrv=/parking | from=::ffff:172.17.0.3 | msg=post to http://perseo_core:8080/perseo-core/events returns {"code":200}
time=2018-09-10T20:41:22.571Z | lvl=INFO | corr=e0e0cbd0-b539-11e8-a247-0242ac110003; perseocep=28 | trans=ab49e201-b502-443b-a234-d939c0518af2 | op=/notices | path=/notices | comp=perseo-fe | srv=city | subsrv=/parking | from=::ffff:172.17.0.3 | msg=done post to http://perseo_core:8080/perseo-core/events
time=2018-09-10T20:41:22.572Z | lvl=INFO | corr=e0e0cbd0-b539-11e8-a247-0242ac110003; perseocep=28 | trans=ab49e201-b502-443b-a234-d939c0518af2 | op=/notices | path=/notices | comp=perseo-fe | srv=city | subsrv=/parking | from=::ffff:172.17.0.3 | msg=sending response: 200 {"error":null,"data":[{"code":200}]}
time=2018-09-10T20:41:22.572Z | lvl=DEBUG | corr=e0e0cbd0-b539-11e8-a247-0242ac110003; perseocep=28 | trans=ab49e201-b502-443b-a234-d939c0518af2 | op=/notices | path=/notices | comp=perseo-fe | srv=city | subsrv=/parking | from=::ffff:172.17.0.3 | msg=response-time: 29 statusCode: 200

**Comment by amfgomez** [comment]
I am thinking that the following line is the cause of the error.
time=2018-09-10T20:41:22.572Z | lvl=INFO | corr=e0e0cbd0-b539-11e8-a247-0242ac110003; perseocep=28 | trans=ab49e201-b502-443b-a234-d939c0518af2 | op=/notices | path=/notices | comp=perseo-fe | srv=city | subsrv=/parking | from=::ffff:172.17.0.3 | msg=sending response: 200 {"error":null,"data":[{"code":200}]}

**Comment by AlvaroVega** [comment]
But that line is about not error

**Comment by amfgomez** [comment]
In this case, I don't understand what's going on

**Comment by AlvaroVega** [comment]
I'm understanding that still is not working for you. Did it work with a previous version (1.6.0 or minor) ?

**Comment by amfgomez** [comment]
Could it be the query?

select *,\"parking-rule2\" as ruleName from pattern [every ev=iotEvent(cast(cast(ev.plazaslibres?,String),int) > 50 and type=\"aparcamiento\")]

**Comment by fgalan** [comment]
Great! :)
