### ISSUE TITLE
How could I do the following example?

### ISSUE THREAD

**Issue by amfgomez** [telefonicaid/perseo-fe#291]
Hello

I am trying to execute the following example:

I have created two entities in orionCB.
service= test
subservice=/subtest

{
"id":"sensor1"
"type":"sensor"
"id_accumulator":"accumulator1"
"typeEvent": 1 //can be 1 or 0
}

{
"id":"accumulator1"
"type":"accumulator"
"used":132
"free":83
"total":200
}

I want that the rules are:

1.- if typeEvent is 1, the used attribute will be plus 1 and the free attribute will be less 1
2.- if typeEvent is 0, the used attribute will be less 1 and the free attribute will be plus 1

is it possible to do with perseo rule and subscription?

Thank you very much.
Best regard

**Comment by amfgomez** [comment]
More information:

when the rules have been executing, the result will be:
-----> typeEvent:1
{
"id":"accumulator1"
"type":"accumulator"
"used":133
"free":82
"total":200
}
---> typeEvent:0
{
"id":"accumulator1"
"type":"accumulator"
"used":131
"free":84
"total":200
}

**Comment by amfgomez** [comment]
https://stackoverflow.com/questions/52889847/how-could-i-do-the-following-example-with-fiware-perseo-fe

**Comment by fgalan** [comment]
Let's close this issue and move dicussion in SOF.

CC: @cblanco
