### ISSUE TITLE
release.sh script doesn't change create-rpm.sh

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#3]
(Similar problem to the one described in https://github.com/telefonicaid/fiware-orion-pep/issues/126)

create-rpm.sh script including the following:

```
if [ -z "$CEP_VERSION" ]; then
  CEP_VERSION=0.4.0_next
fi
```

That `CEP_VERSION=0.4.0_next` is supposed to be changed by release.sh, in order to keep it synchronized regarding the version in the package.json package. However, current release.sh script is not doing so.

**Comment by dmoranj** [comment]
Since the PROXY_VERSION has been removed from create-rpm.sh, this issue isn't needed anymore.
