### ISSUE TITLE
Plain rules with white spaces make perseo crash

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#300]
When a rule has white spaces int he syntax, (e.g. select *,\"regla_sonometros_1\" as ruleName from pattern [every ev=iotEvent((cast(cast(`LAeq`?, String), float)  >=  cast(cast(`thresholdRemote`?, String), float)))]  )

It makes perseo crash. It throws the following error:

time=2018-11-08T12:08:32.353Z | lvl=FATAL | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=error put to http://<host>:<port>/perseo-core/rules (Unexpected end-of-input near ')' at line 1 column 140, please check the filter specification within the pattern expression within the from clause [context ctxt$<service>i$sonometros select *,"regla_sonometros_3" as ruleName from pattern [every ev=iotEvent((cast(cast(`LAeq`?, String), float)  >  65))]])

**Comment by fgalan** [comment]
@cblanco have you faced some time this problem or a similar one?

**Comment by AlvaroVega** [comment]
Maybe using trim() before insert it, or just handle error...

**Comment by fgalan** [comment]
Which particular whitespace is causing the problem?

The examples we use in https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#plain-rules has whitespaces in the EPL fragment, so I understand that whitespaces in EPL are not a problem in general but only in specific parts?

Maybe the problem is whitspace *inside* `cast()` statement?

**Comment by cesarjorgemartinez** [comment]
Two spaces in text field of the cep.rules collection

**Comment by fgalan** [comment]
> Two spaces in text field of the cep.rules collection

Could yo include the text *before* the whitespace removal and *after* the whitespace removal? To see exaclty where the problem is.

**Comment by manucarrace** [comment]
After some investigations, we have found that whitespaces were not the problem. The failing requests have some extrange characters similar to whitespaces (probably introduced by a windows editor) which provoke a sintax error in the EPL query and then the cep raises the error.

This behaviour is correct from the point of view of the CEP.

Issue closed.
