### ISSUE TITLE
[MUST] ReadtheDocs Project remains unmerged

### ISSUE THREAD

**Issue by jason-fox** [telefonicaid/perseo-fe#311]
ReadtheDocs project available and styled using the FIWARE CSS and Chapter CSS - this is a requirement on all Incubated enablers within a reasonable time frame after onboarding

Related PR #304 or equivalent.

- MUST requirement on all GEs from the TSC

**Comment by fgalan** [comment]
I understand PR #304 is related. Not sure, but it seems the discussion between @rafitanba and @jason-fox there didn't reached a conclussion...

**Comment by jason-fox** [comment]
Yes I don't know if #304 should be actioned or withdrawn - it is merely an attempt to fulfill this criterion, hence the link.

**Comment by jason-fox** [comment]
The styled documentation for this project is currently being built from the FICODES fork, the following PR remains unmerged:  https://github.com/telefonicaid/perseo-fe/pull/304

I assume this repo is the master and therefore the documentation should be built directly from this  repo.

The following actions remain incomplete:

1) Merge of the the PR #304 
2) Transfer of the ReadDocs project to point to the new repo: https://readthedocs.org/projects/perseo/

**Comment by fgalan** [comment]
As far as I remember regarding to Perseo documentation, the following PR is ongoing #330. I provided feedback to @cblanco but not all them was addressed.

@cblanco any news on this, please?

**Comment by jason-fox** [comment]
Completed. Closing
