### ISSUE TITLE
NGSIv2 trust token support

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#317]
A follow up PR #305.

Current implementation doesn't support trust tokens in the NGSIv2. This comment mark is in the code:

```
// TODO NGSIv2 update action with trust token (similar to doItWithToken for NGSIv1)
```

This issue is about completing the functionality with that part.

The following line has to be removed in documentation/plain_rules.md when this issue gets completed.

```
 **Note:** NGSIv2 update actions ignore the trust token for now.
```

**Comment by AlvaroVega** [comment]
@fgalan fixed by https://github.com/telefonicaid/perseo-fe/pull/355 ?

**Comment by fgalan** [comment]
I think so. Let's close the issue.

I have adjusted the CNR in PR https://github.com/telefonicaid/perseo-fe/pull/365
