### ISSUE TITLE
Clarify location features in documentation

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#328]
NGSIv2 allows several ways of specifying location: geo:point, geo:line, geo:box, geo:line, geo:polygon and geo:json.

It should be clarifyied in this section of the Perseo FE which formats are supported: https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#location-fields. 

Looking to the current documentation, I tend to think that geo:point will work, but not any of the others. However, this needs to be checked (looking to the code).

In addition, the two links under "The formats are" in that section are pointing to places which seems to be deprecated. They should be fixed.

**Comment by AlvaroVega** [comment]
geo:point is handled in code, but not others like geo:json

**Comment by fgalan** [comment]
Fixed in PR #368
