### ISSUE TITLE
Update docker image

### ISSUE THREAD

**Issue by taliaga** [telefonicaid/perseo-fe#331]
Hi,

Just a heads-up that the Dockerfile needs to be updated. Jessie packages have been moved to archive, so the [update step](https://github.com/telefonicaid/perseo-fe/blob/7d1cea90203290842e5271747725e85f40bcbfb4/Dockerfile#L26) is broken.

For the time being I'm testing the closest official node image (`FROM node:8.15-jessie-slim`), not sure how tests will respond though. You might want to consider updating your node version / dependencies.

By the way, it'd be helpful if you could add automated builds for the docker image. 
Cheers!

**Comment by fgalan** [comment]
Thanks for the feedback!

Upgradinng to node:8.15.1-slim (as in PR #332) seems to fix the problem. According to https://hub.docker.com/_/node/ that image is using Debian Stretch, which is fully mantained by the time being.

With regards to 

> By the way, it'd be helpful if you could add automated builds for the docker image.

Do you refer to a particular dockerhub repository? Which one, pls?

**Comment by fgalan** [comment]
PR #332 fixes this issue in the perseo-fe repository.

Regarding dockerhub automation it is not directly covered in this repository. If you mean the one mantained by the FIWARE Foundation https://hub.docker.com/r/fiware/, they should do the automated build configuration. Maybe @caa06d9c @flopezag could provide guide and support for that.
