### ISSUE TITLE
Create a new action for multiple NGSI filter based updates/appends

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#335]
Design an action that given an NGSI filter do the following:
- make the querycontext operation for the NGSI filter
- apply the NGSI action (update/append) to every result

**Comment by mrutid** [comment]
This action is mandatory to allow schedulling scenarios

**Comment by fgalan** [comment]
A (non exahustive but pretty complete) example:

```
GET /v2/entities?q=temperature>40&mq=humidity.avg==80..90&georel=near;maxDistance:100000&geometry=point&coords=40.418889,-3.691944
```

Probably the best strategy is to store this in a field of the CEP rule in an opaque way, eg:

```
"filter": "q=temperature>40&mq=humidity.avg==80..90&georel=near;maxDistance:100000&geometry=point&coords=40.418889,-3.691944"
```

A side advantage is that any extension of Orion filter can be directly used without any extra modificaiton at CEP.

**Comment by AlvaroVega** [comment]
@fgalan the example that you provide about filter is for a `condition`, isn't it? But what is the example for the `action`?
I understand that this issue should be specified as: New condition + New action.

**Comment by AlvaroVega** [comment]
"action": {
      "type":"query_and_update",
      "parameters":{
          "filter": "q=temperature>40&mq=humidity.avg==80..90&georel=near;maxDistance:100000&geometry=point&coords=40.418889,-3.691944"
          "update": " ¿?"
          }
      }
}

**Comment by AlvaroVega** [comment]
Instead a querystring parameter like:
```q=temperature>40&mq=humidity.avg==80..90&georel=near;maxDistance:100000&geometry=point&coords=40.418889,-3.691944```
A well formed json options like https://conwetlab.github.io/ngsijs/stable/NGSI.Connection.html#.%22v2.listEntities%22__anchor would be desirable:

**Comment by fgalan** [comment]
We could use the "expressions" format used when the query is codified in subscriptions payloads (see http://telefonicaid.github.io/fiware-orion/api/v2/stable/, "Subscriptiosn" section, about the "expressions" field).

For instance, the above filter will be expressed as:

```
"filter": {
    "q": "temperature>40",
    "mq": "humidity.avg==80..90",
    "georel": "near;maxDistance:100000",
    "geometry": "point",
    "coords": "40.418889,-3.691944"
}
```

**Comment by fgalan** [comment]
> Regarding with the example about NGSI filter, @fgalan could you provide an example about NGSI update action?

The idea behind this functionality is that once the rule is triggered (based in the EPL clause) then an update is applied in all entities matching the filter. For instance "update the status attribute to 'on' in all entities of type Lamp.

That would be something like this:

```
"action": {
      "type":"updateFiltered",
      "parameters":{
          "filter": {
              "type": "Lamp"
          }
          "attributes": [
              {
                  "name":"status",
                  "type":"Text",
                  "value":"on"
              }
          ],
          "actionType": "update"
        }
    }
}
```

The CEP will do the following:

1. Do a `GET /v2/entities?type=Lamp` query`
2. For every entity returned by the query, it will do a `PATCH /v2/entities/{id}/attrs - {"status: "on"}` (or equivalent update method currently used for the regular `update` action)

A final comment regarding the action name to use. We can either:

1. Use a different name to `update` (such as `updateFiltered`)
2. Use the same `update` action, making `filter` an optional parameter. If filter is not used, then the behaviour is as it is now ("conventional" update).

Personally I prefer the second one to have a more compact documentation (otherwise we need and extra section in the plain rules documentatio, etc.).

**Comment by fgalan** [comment]
With regards to ngsijs I have been doing a liltle investigation:

* It supports NGSIv2 batch update: http://conwetlab.github.io/ngsijs/stable/NGSI.Connection.html#.%22v2.batchUpdate%22__anchor. This is good, as it would allow to "pack" several entities in a single operation (the only thing to take care is about the 1MB limit in batch operations, so you need to split in several batches if you have more data than that).
* It seems it doesn't support geo-queries. I'm not fully sure, I have opened an issue about it in their repo: https://github.com/conwetlab/ngsijs/issues/27. In the worst case, we can leave that functionality out of CEP action filters in a first version of this feature.

**Comment by fgalan** [comment]
> It seems it doesn't support geo-queries. I'm not fully sure, I have opened an issue about it in their repo: conwetlab/ngsijs#27. In the worst case, we can leave that functionality out of CEP action filters in a first version of this feature.

I have checked (see discussion on the cited issue) that it is actually supported and it just a problem of documentation.

**Comment by fgalan** [comment]
Current update action allows to chose between NGSIv1 and NGSIv2.

The new action should use NGSIv2 (note that filters will not work with NGSIv1). In other words, if the `filter` field is used, then the `version` field is ignored and the API selection is always NGSIv2.

**Comment by AlvaroVega** [comment]
@fgalan is another reason to keep a part updateAction from new queryUpdateAction

**Comment by fgalan** [comment]
Implemented by PR https://github.com/telefonicaid/perseo-fe/pull/360
