### ISSUE TITLE
Check if default values of PERSEO_SMTP_SECURE, and PERSEO_SMTP_TLS_REJECTUNAUTHORIZED are "Falsy" by default [ To be closed] 

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#338]
Check if default values of PERSEO_SMTP_SECURE, and PERSEO_SMTP_TLS_REJECTUNAUTHORIZED are "Falsy" by default, as documentation states. That is, no configuration via config.js and no environment variable setted. We have found some weird behaviour using this.

**Comment by AlvaroVega** [comment]
Regarding with PERSEO_SMTP_TLS_REJECTUNAUTHORIZED if that property is not present as ENV VAR or not included in config.js into config.smtp.tls then that property is not unknown and  nodemailer-smtp-transport will reject all unvalid certs.

Regarding with PERSEO_SMTP_SECURE if that property is not present as ENV VAR or not included in config.js into config.smtp.secure then that property will be false and TLS will not be used.

More details: https://nodemailer.com/smtp/

**Comment by AlvaroVega** [comment]
Shall we close this issue? IMHO no modifications are derived of it.
