### ISSUE TITLE
Interval parameter not working properly in actions [To be closed]

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#339]
The interval parameter is used to avoid repetitive rule executions. It looks like the following:
```
 "action":{
      "type":"update",
      "parameters":{
         "name":"abnormal",
         "value":"true",
         "type":"boolean"
      },
      "interval" : "30e3"
   }
```

We have observed that it works the first time but then, it doesn't work anymore. 

First time the rule is executed right. Second time, the rule is blocked, since it has been executed during the interval, which is also right. More rules executed during the interval are also blocked; right. When the interval is finished, the next execution is fired, which is again right, but from now on, every execution is fired and It is supposed that following executions to the fired rule, within the given interval, should be blocked. 

The following logs are extracted from perseo log (interval set to 90 secs)

time=2019-05-22T16:10:14.245Z | lvl=INFO | corr=15107ba0-7cac-11e9-8ef4-fa163e734aab; perseocep=362993 | trans=997c1ff8-c78d-4aae-9379-cb4d0392c24b | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=demo | subsrv=/xxxxx | msg=executionsStore.Update {"n":1,"nModified":0,"upserted":[{"index":0,"_id":"5ce57466635568f89839afde"}],"opTime":"6693884402591596563","electionId":"5cdea418635568f898e4cad0","ok":1}

time=2019-05-22T16:11:11.326Z | lvl=INFO | corr=371d3fe4-7cac-11e9-8801-fa163e734aab; perseocep=363368 | trans=bdafa17b-47be-4444-b7f5-8297e2d95472 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=demo | subsrv=/xxxxx | msg=discarding action, too recent lastTime 1558541414262 interval 90000 now 1558541471326

time=2019-05-22T16:11:25.489Z | lvl=INFO | corr=3f8d5eca-7cac-11e9-98bc-fa163e734aab; perseocep=362995 | trans=08654ba9-1bc6-4cd1-9560-329e3e45bcde | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=demo | subsrv=/xxxxx | msg=discarding action, too recent lastTime 1558541414262 interval 90000 now 1558541485489

time=2019-05-22T16:11:51.980Z | lvl=INFO | corr=4f5c1c92-7cac-11e9-9548-fa163e734aab; perseocep=362996 | trans=ef51dd0a-46d4-4b17-915d-591472028116 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=demo | subsrv=/xxxxx | msg=executionsStore.Update {"n":1,"nModified":0,"upserted":[{"index":0,"_id":"5ce574c8635568f89839db1a"}],"opTime":"6693884823498391553","electionId":"5cdea418635568f898e4cad0","ok":1}

**time=2019-05-22T16:12:05.697Z | lvl=INFO | corr=5783fe76-7cac-11e9-85bd-fa163e734aab; perseocep=363370 | trans=fdfeb2a4-b718-43c2-af2a-4ec0c13f876b | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=demo | subsrv=/xxxxx | msg=executionsStore.Update {"n":1,"nModified":0,"upserted":[{"index":0,"_id":"5ce574d5635568f89839e595"}],"opTime":"6693884879332966417","electionId":"5cdea418635568f898e4cad0","ok":1}**

**Comment by manucarrace** [comment]
We have observed that exections LastTime value is properly stored in mongo. When there is only one execution in the collection, it works. When there are more than one executions it fails.

**Comment by fgalan** [comment]
Maybe a desperate idea but here we go... :)

This is the part of the code that gets lastime. Not it is using `findOne()` and `sort()`.

```
db.collection(execCollectionName, { strict: true }, function(err, col) {
            if (err) {
                myutils.logErrorIf(err);
                return callback(err, null);
            }
            col.findOne(
                {
                    $query: { name: ruleName, subservice: subservice, service: service, id: id, index: index },
                    $orderby: { lastTime: -1 }
                },
                function(err, data) {
                    myutils.logErrorIf(err);
                    if (err) {
                        return callback(err, null);
                    }
                    return callback(null, (data && data.lastTime && data.lastTime.getTime()) || 0);
                }
            );
        });
```
I'd suggest to use `find()` + `limit(1)` instead of `findOne()`. Not sure how the driver is "mapping" this to MongoDB and maybe it is ignoring order and returning always the first element.

**Comment by AlvaroVega** [comment]
It seems that orderby is deprecated since 3.2 https://docs.mongodb.com/manual/reference/operator/meta/orderby/ so we can change to find + sort + limit

**Comment by fgalan** [comment]
> It seems that orderby is deprecated since 3.2 https://docs.mongodb.com/manual/reference/operator/meta/orderby/ so we can change to find + sort + limit

Great! So my idea was not so desperate at the end :)

**Comment by AlvaroVega** [comment]
Possible fix: https://github.com/telefonicaid/perseo-fe/pull/340

**Comment by fgalan** [comment]
PR #340 has been merged but let this issue opened while it can be checked if that solves this issue.
