### ISSUE TITLE
Casting to float

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#345]
In order to make a casting to float it is needed to make the following
`(cast(cast(`battery`?, String), float)`

If we make `(cast(`battery`?, float)` the rule does not work as expected.

**Comment by AlvaroVega** [comment]
In ` (cast(battery?, float) ` is there a missed `)` ?

**Comment by fgalan** [comment]
Is this actually a problem with Perseo? Or just a consequence of how EPL works?

**Comment by AlvaroVega** [comment]
Could you provide a full example (rule, action, data, expected data) ?

**Comment by AlvaroVega** [comment]
if there is a `temperature` attribute of type Number, or inserted in ContextBroker as a real numerical type then you don't need to cast to string, just just to float:
```
select *, *, ev.temperature? as Temperature,  ev.id? as Meter from pattern [every ev=iotEvent(cast(temperature?,float)>1.5)]
```

**Comment by mrutid** [comment]
**Two nested cast expression are needed if you expect to receive Strings representing Numbers is your context stream.**

Examples and explanation:

Every Dinamic Property (fillingLevel?) has Object type in Esper, therefore casting is needed to use fillingLevel in float expressions.
<img width="1056" alt="image" src="https://github.com/telefonicaid/perseo-fe/assets/968372/3430b000-d71c-4315-b9c2-7ed2364a28b2">

If we do the float cast it works when fillingLevel is a number (int or float). But fails if it's a String containing a number (in fact an Object containing a String "containing" a number):
<img width="789" alt="image" src="https://github.com/telefonicaid/perseo-fe/assets/968372/99395c86-3bee-4009-a70c-1408b3a31e1b">

If we resolve the Object to String (which works almost every time) then we can safety cast to float:
<img width="739" alt="image" src="https://github.com/telefonicaid/perseo-fe/assets/968372/465d6c0c-9d12-477a-973d-249d79dd424b">

In this case if filling level contains a value uncasteable to float ("PATATA") an exception occurs, so rule doesn't get fired.

**Comment by AlvaroVega** [comment]
It would be nice document that explanation https://github.com/telefonicaid/perseo-fe/issues/345#issuecomment-1625123336 into doc about EPL usage https://github.com/telefonicaid/perseo-fe/blob/master/docs/API/plain_rules.md#epl-text
