### ISSUE TITLE
Create new action to create/update/delete an entity from another service/subservice path

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#349]

**Comment by fgalan** [comment]
Proposal: extend current "update" action with a couple of new fields for "service" and "subservice" (default: the same service of subservice of the triggering entity, to keep backward compatibility):

```
"action":{
        "type":"update",
        "parameters":{
            "id":"${id}_mirror",
            "attributes": [
                {
                    "name":"abnormal",
                    "type":"boolean",
                    "value":"true"
                }
            ],
            "service": "newserv",
            "service": "/newsubserv",
            "actionType": "UPDATE"
        }
    }
```

**Comment by fgalan** [comment]
The "delete" in "create/update/delete" requires to complete #350 first

**Comment by AlvaroVega** [comment]
It seems that currenty updateAction card is able of use service and subservice to get a token for a another service/subservice....

**Comment by fgalan** [comment]
> It seems that currenty updateAction card is able of use service and subservice to get a token for a another service/subservice....

Do you mean the "internal capability" in the code? Or we can even set a different service/subservice in the rule JSON?

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#update-attribute-action

There is a optional parameter for update action

trust: optional, trust token for getting an access token from Auth Server which can be used to get to a Context Broker behind a PEP.

**Comment by fgalan** [comment]
This seems to be the PR that implemented trust token: https://github.com/telefonicaid/perseo-fe/pull/85

Just in case it may be uselful...

**Comment by AlvaroVega** [comment]
In case of use trust/token you should provide a proper perseo configuration for 
```
config.authentication = {
    host: 'keystone',
    port: '5001',
    user: 'user',
    password: 'password'
};
```
https://github.com/telefonicaid/perseo-fe/blob/master/config.js#L154
but unfortunately that config is not prepared to use as env var for docker.

**Comment by fgalan** [comment]
Variables added in PR https://github.com/telefonicaid/perseo-fe/pull/399

Anything pending on this issue or can it be closed?

**Comment by fgalan** [comment]
Implemented in PR https://github.com/telefonicaid/perseo-fe/pull/435
