### ISSUE TITLE
Create new action to delete an entity

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#350]

**Comment by fgalan** [comment]
(Removing "and from another service/subservice path" as this is actually part of #349 in general for all the update actions, i.e. actual update, creation or deletion)

**Comment by fgalan** [comment]
Actually, instead of a new action, it would be matter of adding "actionType": "delete" to the set of supported action types for the existing "update" action.

**Comment by AlvaroVega** [comment]
Currently perseo is using NGSI v1 or v2 to update entity:
- v1: API /v1/updateContext with body
```
  {
        contextElements: [
            {
                isPattern: options.isPattern,
                id: options.id,
                attributes: options.attributes
            }
        ],
        updateAction: 'APPEND'
    }
```

- v2  
     is using https://github.com/conwetlab/ngsijs which encapsules  updateAction

**Comment by fgalan** [comment]
> v2: is using https://github.com/conwetlab/ngsijs which encapsules updateAction

This is weird... why don't just use the equivalente to NGSIv2 of the NGSIv1 payload. I mean (if I'm remember correctly):

```
  {
        entities: [
            {
                id: options.id,
                <map with the attributes>
            }
        ],
        actionType: 'append'
    }
```

Could you include the link to the part of the code using conwetlab/ngsijs (to better understand this), please?

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/perseo-fe/blob/master/lib/models/updateAction.js#L321

**Comment by AlvaroVega** [comment]
Done in https://pdihub.hi.inet/fiware/iotp-nitro-components/pull/11
