### ISSUE TITLE
VisualRule for Twitter action

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#358]
Current plain action twitter does not have a GUI based on VisualRule:
https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#actions

**Comment by fgalan** [comment]
Taking into account there is a removal plan for Visual Rules (issue https://github.com/telefonicaid/perseo-fe/issues/734), this issue doesn't make sense. Closing.
