### ISSUE TITLE
Cannot access to array elements in perseo events

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#361]
In the same way as specified in https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#location-fields

It would be nice to have support for geo:json values in order to refer to location values in actions.

A notice with a location field in the following form:
{"subscriptionId":"5d7763a1304a983349138bc2","originator":"localhost","contextResponses":[{"contextElement":{"type":"Streetlight","isPattern":"false","id":"farolahttpngsi","attributes":{"name":"location","type":"geo:json","value":{"type":"Point","coordinates":[-0.036685,39.985159]}}]},"statusCode":{"code":"200","reasonPhrase":"OK"}}]}

will generate the event:
{"ev":{"location__coordinates__1":39.985159,"location__coordinates__0":-0.036685,"noticeTS":1568641876519,"type":"Streetlight","isPattern":"false","noticeId":"0dcd5370-d889-11e9-8993-2f3dac0e41ef","subservice":"/castellon","service":"demo","id":"farolahttpngsi","location__type":"geo:json"},"ruleName":"alarma_lampara","timeinstant":"2019-09-16T13:51:16.475Z"}

But it is not possible to access to "location__coordinates__0" or "location__coordinates__1"  in the rule:

```
{
    "name": "alarma_lampara",
    "text": "select *, \"alarma_lampara\" as ruleName, ev.location__coordinates__1? as long, ev.location__coordinates__0? as lat,  from pattern [every ev=iotEvent(type='Streetlight')]",
    "action": [
        {
            "type": "update",
            "parameters": {
                "id": "${id}",
                "type": "Streetlight",
                "attributes": [
                    {
                        "name": "location",
                        "type": "geo:json",
                        "value": {
                            "type": "Point",
                            "coordinates": [
                                "${lat}",
                                "${long}"
                            ]
                        }
                    }
                ],
                "actionType": "append"
            }
        }
    ]
}
```

**Comment by manucarrace** [comment]
Also it have been tested to send the location as it is received but is provokes an error in CB.

The rule is:
{
"name": "alarma_lampara",
"text": "select *, "alarma_lampara" as ruleName, ev.location? as location, from pattern [every ev=iotEvent(type='Streetlight')]",
"action": [
{
"type": "update",
"parameters": {
"id": "${id}",
"type": "Streetlight",
"attributes": [
{
"name": "location",
"type": "geo:json",
"value": ${location}
}
],
"actionType": "append"
}
}
]
}



The error in CB is:
time=2019-09-16T13:03:51.253Z | lvl=DEBUG | corr=6dceb73e-d882-11e9-904e-fa163e0622ea; perseocep=86219 | trans=233cc343-5151-4d63-860c-728f44e1f552 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=demo | subsrv=/castellon | msg=post to http://10.0.0.2:1026/v1/updateContext returns {"code":200,"body":{"contextResponses":[{"contextElement":{"type":"Alert","isPattern":"false","id":"malfunction:farolahttpjson","attributes":[{"name":"location","type":"geo:json","value":""}]},"statusCode":{"code":"472","reasonPhrase":"request parameter is invalid/not allowed","details":"action: APPEND - entity: [malfunction:farolahttpjson, Alert] - offending attribute: location - error parsing location attribute for new attribute: geo:json needs an object as value"}}]}}

**Comment by manucarrace** [comment]
moved to https://github.com/telefonicaid/perseo-fe/issues/362

**Comment by fgalan** [comment]
According to Perseo documentation at btw, esta es la documentación en la que se basa lo que digo: https://github.com/telefonicaid/perseo-fe/tree/master/documentation/plain_rules.md#metadata-and-object-values, Perseo is able to access to sub-keys in a JSON value for an attribute.

I guess the problem is when trying to access to an element in an array. So, maybe we should support the `[]` operator along with currently supported `.` operator.

In addition, proper support to GeoJSON points (ie. attribute type is "geo:json" and GeoJson type is "Point") alisnged with https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#location-fields good be great (that is, to propagate the lat and long coordiantes with the special lat/lon and x/y events).

**Comment by AlvaroVega** [comment]
There is no problem to have an action like:
```
{
      "type": "update",
      "parameters": {
          "filter": {
              "type": "thing"
          },
          "version": 2,
          "attributes": [
              {
                  "name":"latitud",
                  "type":"MiTipo",
                  "value":"${Lat}"
              },
              {
                  "name":"longitud",
                  "type":"MiTipo",
                  "value":"${Lon}"
              },
         ],
          "actionType": "update"
    }
}
```
with 
select *, *, ev.temperature? as Temperature, ev.location__coordinates__1? as Lat, ev.location__coordinates__0? as Lon, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(temperature?,String),float)>1.5)]

**Comment by fgalan** [comment]
So it seems we can access to array values in attributes with `__0`, `__1`, etc. but it is not documented in https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md (or maybe it is but I'm missing  it?)

In that case, the documentation gap should be addressed as part of this issue.

**Comment by AlvaroVega** [comment]
Currently there are some description about 
- metadatas and objects: https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#metadata-and-object-values
- locations:  https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#location-fields
- time fields: https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#time-fields

**Comment by fgalan** [comment]
> We can add a description for generic Arrays and jSONs

Maybe as part of the first section, renaming it: "Metadata and object values" -> "Metadata and object/array values" (or something like that).

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/perseo-fe/pull/371
