### ISSUE TITLE
New functionality for expanded Vars

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#362]
Right now only string values can be expanded in action. 

We miss the ability to expand numbers, boolean or Json values. As far as it is necessary to use string in the action template in order to write a valid action JSON i.e: {"Mynuml": ${num}} is not a valid JSON. Some kind of convention seems to be needed.

For example: if a value in an action template "${val}" contains only the placeholder itself without any other character, we should return the proper value and not the stringyfied value.  

So  {"Mynum": "${num}"} will expand as  {"Mynum": 42} and not to  {"Mynum": "42"}.

Same for Json values so {"Myjson": "${json}"} will expand as  {"Myjson": {"hello":"world"}} and not to  {"Myjson": "{/"hello/":/"world/"}"} 

https://github.com/telefonicaid/perseo-fe/blob/5f51a843dbf0ec5146f7acf47d3af84a5668247b/lib/myutils.js#L54

**Comment by AlvaroVega** [comment]
There is also a expandObject https://github.com/telefonicaid/perseo-fe/blob/master/lib/myutils.js#L64

**Comment by mrutid** [comment]
How it works?

**Comment by AlvaroVega** [comment]
I this for an updateAction based on **version 2** like:
action:
```
{
      "type": "update",
      "parameters": {
          "filter": {
              "type": "thing"
          },
          "version": 2,
          "attributes": [
              {
                  "name":"status",
                  "type":"Text",
                  "value":"${Temperature}"
              }
          ],
          "actionType": "update"
    }
}
```
its is working because

https://github.com/telefonicaid/perseo-fe/blob/master/lib/models/updateAction.js#L276
for types:
Text
Number
Boolean
DateTime

**Comment by fgalan** [comment]
The new way in which var expansion works (based in the text from @mrutid ) should be documented. I think is this place: https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#string-substitution-syntax

**Comment by AlvaroVega** [comment]
PR for addresshttps://github.com/telefonicaid/perseo-fe/issues/362#issuecomment-536582285   https://github.com/telefonicaid/perseo-fe/pull/373

**Comment by AlvaroVega** [comment]
Regarding with:

Same for Json values so {"Myjson": "${json}"} will expand as {"Myjson": {"hello":"world"}} and not to {"Myjson": "{/"hello/":/"world/"}"}

$json only can expand values from EV, but in an EV a JSON is decomposed in several entries like we explain in:
https://github.com/telefonicaid/perseo-fe/blob/be69b75032863b851589826ea919f4dd3228b4d3/documentation/plain_rules.md#json-and-array-fields
