### ISSUE TITLE
support paging options in API /rules 

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#364]
A reference about paging options could be fiware-orion

 https://fiware-orion.readthedocs.io/en/master/user/pagination/index.html

**Comment by AlvaroVega** [comment]
related with https://github.com/telefonicaid/perseo-fe/pull/356

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/396

**Comment by fgalan** [comment]
Does PR #396 completes this issue? Or there is something else pending after it?

**Comment by AlvaroVega** [comment]
#396 competes this issue
