### ISSUE TITLE
include json stripped into event

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#377]
Currently event is mapped an used like:

```json
{"noticeId":"95eb1940-e450-11e9-93cb-7d4a62c71ec2","noticeTS":1569937037524,"id":"thing:disp1","type":"thing","isPattern":"false","subservice":"/","service":"smartcity","TimeInstant":"2019-10-01T13:37:20.00Z","TimeInstant__type":"DateTime","TimeInstant__ts":1569937040000,"TimeInstant__day":1,"TimeInstant__month":10,"TimeInstant__year":2019,"TimeInstant__hour":13,"TimeInstant__minute":37,"TimeInstant__second":20,"TimeInstant__millisecond":0,"TimeInstant__dayUTC":1,"TimeInstant__monthUTC":10,"TimeInstant__yearUTC":2019,"TimeInstant__hourUTC":13,"TimeInstant__minuteUTC":37,"TimeInstant__secondUTC":20,"TimeInstant__millisecondUTC":0,"copia__type":"MiTipo","copia__coordinates__0":28,"copia__coordinates__1":23,"location__type":"string","location__coordinates__0":23,"location__coordinates__1":28,"open":true,"open__type":"Boolean","temp":44,"temp__type":"Number","tempLatitud":28,"tempLatitud__type":"MiTipo","tempLocation":"28,23","tempLocation__type":"MiTipo","tempLongitud":23,"tempLongitud__type":"MiTipo","temperature":44,"temperature__type":"Number"}
```

Including several entries for each field of a json, like:
 location__type
 location_coordinates
 location_coordinates_0
 location_coordinates_1
instead of location `{ type: "", coordinates: [1,2 ] }`

we want include in adition original json stringyfied into event

related https://github.com/telefonicaid/perseo-fe/issues/361

**Comment by fgalan** [comment]
> we want include original json stringyfied into event

In _addition to_ current

location__type
location_coordinates
location_coordinates_0
location_coordinates_1

or _instead of_ them?

**Comment by AlvaroVega** [comment]
in addition

**Comment by AlvaroVega** [comment]
This is the function in charge of flatter a JSON object into event: https://github.com/telefonicaid/perseo-fe/blob/master/lib/myutils.js#L98

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/393/
