### ISSUE TITLE
Review an align update action v2 test to cover the same as v1

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#380]

**Comment by fgalan** [comment]
It seem the updateActions.js module is required only in two unit test files:

* axn_param_utest.js, within the "#buildUpdateOptions()` group. 

![imagen](https://user-images.githubusercontent.com/1534240/66042073-c2683e00-e51b-11e9-95a3-55f761671b99.png)

They only test the updateAction.buildUpdateOptions() method, which is understand is orthogonal to independent of the NGSI API version.

* updateAction.js. It sets `version: 2` and include the following cases:

![imagen](https://user-images.githubusercontent.com/1534240/66042191-1bd06d00-e51c-11e9-826c-cb8039652a9a.png)

Looking to the coverage report for that file https://coveralls.io/builds/26063203/source?filename=lib/models/updateAction.js I think they cover pretty good the code, with two exceptions (big blocks in red):

* processUpdateOptionParams(). Seem to be similar to processOptionParams(), which is covered. Maybe both methods can be unified? Maybe it's related (or to be solved by) PR https://github.com/telefonicaid/perseo-fe/pull/376
* doItWithTokenV2(). Seems to be pretty similar to doItWithToken(). Maybe it's a matter of find which test is covering doItWithToken() and do a copy-adaptation for NGSIv2

**Comment by AlvaroVega** [comment]
processUpdateOptionParams() and  processOptionParams() are not so similar, one expect event ant other expect entity.
doItWithTokenV2 and  doItWithToken() are quite similar, and a refactor is possible.

**Comment by AlvaroVega** [comment]
possible refactor https://github.com/telefonicaid/perseo-fe/pull/383 WIP

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/408 includes a nuw utest case that exercises  processOptionParams().

I think that after that there isn't anything pending and the issue can be closed.
