### ISSUE TITLE
Unify usage of "service" and "subservice" in all the code

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#39]
(Raised in https://github.com/telefonicaid/perseo-fe/pull/37)

We should rationalize the usage of the service and subservice concetps in the code. Currently, there some problems:

* The usage of old term "tenant" for service
* The usage of "service" in places where actually it means "subservice"

So, a overall review of the code is needed to fix all this things and make code more maintenable.

**Effort: 2 man day**

**Comment by crbrox** [comment]
I think this can be closed by #88
