### ISSUE TITLE
validation of service (tenant) and service path in header

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#4]
@iariasleon issue:

When create a epl rule (POST /rules), we recommend validate these headers

Info in Context Broker:
```
https://forge.fi-ware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#Multi_service_tenancy
```

```
https://forge.fi-ware.org/plugins/mediawiki/wiki/fiware/index.php/Publish/Subscribe_Broker_-_Orion_Context_Broker_-_User_and_Programmers_Guide#Entity_service_paths
```

Effort: 2 man day

**Comment by fgalan** [comment]
Which speciffic headers do you refer to? Which kind of validation?

**Comment by iariasleon** [comment]
my idea is validate service and service path with values allowed ex:
``` 
- Service/tenant: it must be a string of alphanumeric characters (and the "_" symbol). Maximum length is 50 characters.
```
```
- Service path:Scope must start with "/" (only 'absolute' scopes are allowed), 50 maximum characters in each level (before release 0.17.0 it was 10), only alphanum and underscore allowed and Fiware-ServicePath is an optional header.
```

**Comment by fgalan** [comment]
I agree, CEP should validate that headers (in the same way CB does it).

Thus, I'd suggest to evolve this issue from "question" to tech debt (category "must").

**Comment by fgalan** [comment]
From Orion CB documentation (service path syntax should follow same rules):

> * Limitations:
>  * Scope must start with "/" (only 'absolute' scopes are allowed)
>  * 10 maximum scope levels in a path
>  * 50 maximum characters in each level, only alphanum and underscore allowed
> * Fiware-ServicePath is an optional header. It is assumed that all the entities created without Fiware-ServicePath (or that don't include service path information in the database) belongs to a root scope "/" implicitely. 
> * Rules [in CB was Entities] belongs to one (and only one) scope.

**Comment by crbrox** [comment]
Resolved by #37 ?

**Comment by fgalan** [comment]
I think this could be closed.

@iariasleon or @jcalderin : could you close this issue if you agree, please?

**Comment by iariasleon** [comment]
LGTM

**Comment by iariasleon** [comment]
Tested in:
  - test/acceptance/integration/Rules/EPL/epl_create_rules.feature
  - test/acceptance/integration/Rules/EPL/epl_delete_rules.feature
  - test/acceptance/integration/Rules/EPL/epl_read_rules.feature
