### ISSUE TITLE
create a version reponse - Perseo-fe

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/perseo-fe#41]
Create a version request (http) or message in log to Perseo-fe.
examples: 
```
http://host:port/version
```
```
In log when start Perseo
```

**Comment by fgalan** [comment]
This is the repo for Perseo FE. Please, create a dual-issue also in the Perseo Core repo (issues covering both repos traversaly are not a good idea...).

**Comment by fgalan** [comment]
Implemented in PR #82
