### ISSUE TITLE
Temporal rules does not work after restart

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#411]
In the event of a restart, the temporal rules stop working. 

It is also known that temporal rules need a context started (or active) to work, that means that a initial foo notification must be sent.

Both problems are related. We should avoid initial notification or send automatically these initial notifications in case of restart or new time-rule provision.

**Comment by manucarrace** [comment]
Example of temporal rule:

{
	"name":"Timer_example",
	"text":"select *, current_timestamp.toDate() as currentTS from pattern [every timer:interval(10 sec)]",
	"action": [{
		"type":"update",
		"parameters":{
			"id":"timer_example_min_2",
			"type": "ww",
			"attributes": [
				{
					"name":"timestamp",
					"type": "Text",
					"value": "${currentTS}"
				}
			]
		}
	}]
}

**Comment by fgalan** [comment]
@cblanco @aarranz you did some modifications in Perseo Core related with time rules in the past (PR https://github.com/telefonicaid/perseo-core/pull/114). What do you think about this? Any idea?

**Comment by manucarrace** [comment]
Using the ESPER simulator:

If we include the time-rule in a partitioned context it does not work:

![Captura de pantalla 2019-11-08 a las 13 08 21](https://user-images.githubusercontent.com/7370473/68475948-c3327500-0229-11ea-9c27-e007926d8d9f.png)

If then, we estimulate with an event, then it works:

![Captura de pantalla 2019-11-08 a las 13 08 59](https://user-images.githubusercontent.com/7370473/68476018-eceb9c00-0229-11ea-841d-121b85a0a5b1.png)

Creating a specific context for time-rules it seems to work:

![Captura de pantalla 2019-11-08 a las 13 08 02](https://user-images.githubusercontent.com/7370473/68476076-13113c00-022a-11ea-9f3a-9d61122e5fa0.png)

This could be the solution.

**Comment by fgalan** [comment]
Fixed in PR #415
