### ISSUE TITLE
deleteAction

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#436]
Similar to updateAction, but deleting entity

**Comment by fgalan** [comment]
We have been discussing at skype than mabye with the existing udpate action with actionType = DELETE action is enough

I'd suggest hold on this issue for a while, until we get a better understadning of this (maybe after @manucarrace testing)

**Comment by AlvaroVega** [comment]
See https://github.com/telefonicaid/perseo-fe/pull/437
