### ISSUE TITLE
"cc" or "bcc" usage in email type action

### ISSUE THREAD

**Issue by agaldemas** [telefonicaid/perseo-fe#444]
is it possible to put several recipients in parameters.to attribute of an email type action ?
something like:

 ```
  "action": {
        "type": "email",
        "template": "So glad with our new ${role}, ${id}!",
        "parameters": {
            "to": "someone@tid.es, anotherone@tid.es, anothertwo@tid.es",
            "from": "system@iot.tid.es",
            "subject": "Welcome ${id}!"
        }
    }

```
Thanks in advance for your kind answer.

**Comment by agaldemas** [comment]
I checked Nodemailer lib, can take several recipients in the "to" field (comma separated or array), so it should work
will test to check, if it works !
but what about using "cc" or "bcc" ?

**Comment by fgalan** [comment]
>  will test to check, if it works !

Great! Please report the result of your check in this issue as comment, pls.

>  but what about using "cc" or "bcc" ?

Usually with "to" is enough. But if you want to propose an extension to Perseo included that (it shouldn't bee too complex... just a matter of looking how "to" is done and do it in a similar way) we would be more than happy to review the PR with the contribution :)

**Comment by agaldemas** [comment]
Hi  @fgalan, nice to read you again, 
OK, I think I can add the feature, bcc, through a PR, since it will allow to hide other mail recipients, this can be useful for alert diffusion, in particular for the project we are working on !

for the test of multiple recipients, i'm about to do it, 
but i'm facing an issue with Orion 2.4, to send notifications to perseo-fe, 
something I can't catch for the moment...
So, may be, you should see me soon on fiware-orion....

**Comment by fgalan** [comment]
>  OK, I think I can add the feature, bcc, through a PR, since it will allow to hide other mail recipients, this can be useful for alert diffusion, in particular for the project we are working on !

@agaldemas any update on this, please? Thanks!

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/520 implements this.

@agaldemas maybe you could test it and tell us how it goes, please? Use the `:latest` tag at dockerhub after waiting a while (the PR has been just merged and the container maybe has not been built yet)
