### ISSUE TITLE
Documentation API /version POST instead of GET

### ISSUE THREAD

**Issue by agaldemas** [telefonicaid/perseo-fe#445]
in  [api.md](https://github.com/telefonicaid/perseo-fe/blob/master/documentation/api.md)
Method | Path | Description
-- | -- | --
POST | /version | Get version of perseo

should be

Method | Path | Description
-- | -- | --
GET | /version | Get version of perseo

using POST return an error !

**Comment by fgalan** [comment]
Thanks for the report!

It seems to be an easy fix... Maybe you could do a PR with the fix, please? Thanks!

**Comment by fgalan** [comment]
Fixed by PR #477
