### ISSUE TITLE
In post action, the  "URL" parameter is better to change in lowercase as said in doc

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/perseo-fe#45]
In the documentation:
https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#http-post-action

said that:
```
"parameters": {
            "url": "localhost:1111"
        }
```
but in code is used "URL" in uppercase.
```
"parameters":{
            "URL":"localhost:1111"
       }
```
It is better to change the code to make it the same as mentioned in the doc

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/perseo-fe/pull/54. @iariasleon please close this issue once you have checked that is fixed.

**Comment by iariasleon** [comment]
LGTM
```
"action":{
    "type":"post",
    "parameters":{
        "url":"http://localhost:1111"
    },
....
```
