### ISSUE TITLE
FILTERED UPDATE ACTION: List All Entities

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#455]
Now it is possible to use the "limit" key to specify the max number of entities involved be the filter. But it's possible that we want to include all the entities that fulfill a given filter. In this way some option should be included in order to determine the total count of possible results and iterate thought the whole set.

**Comment by AlvaroVega** [comment]
NGSIv2 pagination options: https://fiware-orion.readthedocs.io/en/latest/user/pagination/index.html

NGSIv2 simple query language: https://jsapi.apiary.io/previews/null/introduction/specification/simple-query-language

https://conwetlab.github.io/ngsijs/stable/NGSI.Connection.html#.%22v2.batchQuery%22
 v2.batchQuery(query [, options])
    [options] | Object | Object with extra options:
        count (Boolean; default: false): Request total count
        limit (Number; default: 20): This option allow you to specify the maximum number of entities you want to receive from the server
        offset (Number; default: 0): Allows you to skip a given number of elements at the beginning

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/492
