### ISSUE TITLE
false loop detection in HA

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#456]
If two perseo-fe nodes (i.e. in a HA deploy) were started at the same time then they will handle the same counter for compose correlator (adding perseo-cep=<counter>):
```
corr=b6ab6d76-c0da-11ea-9688-fa163e83ea20; perseocep=8581
```

Then sometimes loop detection at https://github.com/telefonicaid/perseo-fe/blob/master/lib/routes/actionsController.js#L54 is detecting a loop since a correlator occurrence is detected.

It would be desirable correlator will be unique by node (i.e. using a unique id for that perseo-cep instead a counter)

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/457
