### ISSUE TITLE
crash posting action with number instead a proper json

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#459]
log example: 

time=2020-10-06T14:57:43.119Z | lvl=INFO | corr=4970351a-07e4-11eb-bc2d-0242ac11001a; perseocep=39 | trans=80576df9-e70e-4685-8b33-327221f4c0a4 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=alcobendas | subsrv=/residuos | msg=making post to https://enxsg20jrp8.x.pipedream.net
time=2020-10-06T14:57:43.120Z | lvl=ERROR | corr=4970351a-07e4-11eb-bc2d-0242ac11001a; perseocep=39 | trans=80576df9-e70e-4685-8b33-327221f4c0a4 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=alcobendas | subsrv=/residuos | msg=error post to https://enxsg20jrp8.x.pipedream.net Argument error, options.body.
time=2020-10-06T14:57:43.120Z | lvl=ERROR | corr=4970351a-07e4-11eb-bc2d-0242ac11001a; perseocep=39 | trans=80576df9-e70e-4685-8b33-327221f4c0a4 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=alcobendas | subsrv=/residuos | msg=https://enxsg20jrp8.x.pipedream.net Argument error, options.body.
time=2020-10-06T14:57:43.120Z | lvl=INFO | corr=4970351a-07e4-11eb-bc2d-0242ac11001a; perseocep=39 | trans=80576df9-e70e-4685-8b33-327221f4c0a4 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=alcobendas | subsrv=/residuos | msg=https://enxsg20jrp8.x.pipedream.net null
time=2020-10-06T14:57:43.123Z | lvl=FATAL | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | msg=uncaughtException: The first argument must be one of type string or Buffer. Received type number TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string or Buffer. Received type number,    at write_ (_http_outgoing.js:595:11),    at ClientRequest.write (_http_outgoing.js:567:10),    at Request.write (/opt/perseo-fe/node_modules/request/request.js:1500:27),    at end (/opt/perseo-fe/node_modules/request/request.js:549:18),    at Immediate.<anonymous> (/opt/perseo-fe/node_modules/request/request.js:578:7),    at runCallback (timers.js:705:18),    at tryOnImmediate (timers.js:676:5),    at processImmediate (timers.js:658:5),    at process.topLevelDomainCallback (domain.js:126:23)

Using an actions like:
```
"action": {
"type": "post",
"template": 234,
"parameters": {
"method": "POST",
"url": "https://enxsg20jrp8.x.pipedream.net",
"headers": {
"Content-type": "text/plain"
}
}
}
```

**Comment by AlvaroVega** [comment]
the point of crash is: https://github.com/telefonicaid/perseo-fe/blob/master/lib/myutils.js#L161

 bodySz = Buffer.byteLength(8)
Thrown:
TypeError [ERR_INVALID_ARG_TYPE]: The "string" argument must be one of type string, Buffer, or ArrayBuffer. Received type number
    at Function.byteLength (buffer.js:514:11

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/462
