### ISSUE TITLE
Append to doc a case with json template to POST action

### ISSUE THREAD

**Issue by iariasleon** [telefonicaid/perseo-fe#46]
Append a doc a case with json template to POST action, example:
```
{"action": {"type": "post", "parameters": {"URL": "http://qa-orion-cep-01:9998/send/post"}, "template": "{\"message\": \"Element ${Meter} has value <<<${attrName_0_var}>>> \\n -- (post rule)\"}"}, "text": "select *,\"post___name\" as ruleName, \"/\" as service, \"unknownT\" as tenant, *, ev.at
trName_0? as attrName_0_var, ev.id? as Meter from pattern [every ev=iotEvent(cast(cast(attrName_0?,String),float)>1.5 and type=\"room\")]", "name": "post___name"}
```
Further, use only JSON format.

**Effort: 1 man day**

**Comment by fgalan** [comment]
If this is a tech debt issue, it should include an effort measure, as in other. I have set 1 man day, but feel free to change it if you think it needs more time.

**Comment by crbrox** [comment]
I think this could be seen as solved at https://github.com/telefonicaid/perseo-fe/blob/develop/documentation/plain_rules.md#http-post-action

Can be closed?

 I add @jcalderin

**Comment by fgalan** [comment]
I agree in closing this. Pleas, @jcalderin close it if you agree.

**Comment by crbrox** [comment]
It should be closed by 9d51f2a in #112

**Comment by fgalan** [comment]
@iariasleon , have a look and close this if you think doc is now ok.

**Comment by iariasleon** [comment]
LGTM
