### ISSUE TITLE
CEP no signal rules: check setinterval

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#464]
v8:  2,147,483,647ms

cep: 288099 * 60 * 1000 = 17,285,940,000ms >>> 2,147,483,647ms

“Be careful that if you make the number bigger than that, it will run immediately (Imaging that you put a negative value, so the browser will run infinitely loop)”

**Comment by AlvaroVega** [comment]
Currently min value is checked https://github.com/telefonicaid/perseo-fe/blob/master/lib/models/noSignal.js#L166 and then warn and set to minimum value.
In the same way we can checkit, warn, and set to max value allowed. Proposal: https://github.com/telefonicaid/perseo-fe/pull/465

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/465
