### ISSUE TITLE
'null' instead of '[?]' when no data available for macro substitution

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#469]
If there is an action with a macro
```json
	"action": {
        "type": "update",
        "parameters": {
            "attributes": [
                {
            		"name": "dateCalculatedIncrement",
                        "type": "DateTime",
            		"value": "${timeinstant}"
            	}
            ]
        }
    }
```

and the value of ${timeinstant} can not be retrieved, the value updated to the CB is "[?]".

It should be nice to set the value to null instead.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/476

Should this issue be closed or is there anything pending?
