### ISSUE TITLE
timing rule broken when no entity is returned by CB

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#485]
time=2021-01-29T12:53:08.876Z | lvl=INFO | corr=377b0811-b0c9-4230-9c7c-c98ed4416a59; node=jKUzSyLEg; perseocep=18 | trans=01559ae6-9564-4f99-9409-1321f42690a7 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=alcobendas | subsrv=/inmotica | from=Perseo-core-timer-rule | msg=incoming request {​​​​​​​"method":"POST","url":"/actions/do","headers":{​​​​​​​"content-type":"application/json; charset=utf-8","fiware-correlator":"377b0811-b0c9-4230-9c7c-c98ed4416a59","fiware-service":"alcobendas","fiware-servicepath":"/inmotica","x-real-ip":"Perseo-core-timer-rule","cache-control":"no-cache","pragma":"no-cache","user-agent":"Java/1.8.0_252","host":"172.17.0.1:19090","accept":"text/html, image/gif, image/jpeg, *; q=.2, */*; q=.2","connection":"keep-alive","content-length":"76"}​​​​​​​,"body":{​​​​​​​"ruleName":"arrancaTemporizacion","timeinstant":"2021-01-29T12:53:08.874Z"}​​​​​​​,"subservice":"/inmotica","service":"alcobendas"}​​​​​​​
time=2021-01-29T12:53:08.880Z | lvl=INFO | corr=n/a | trans=n/a | op=n/a | msg=rulesStore.Find {​​​​​​​"_id":"601404e4fab4f86d7e91023d","name":"arrancaTemporizacion","text":"select \"arrancaTemporizacion\" as ruleName, *, curre 

time=2021-01-29T12:53:08.889Z | lvl=WARN | corr=377b0811-b0c9-4230-9c7c-c98ed4416a59; node=jKUzSyLEg; perseocep=18 | trans=01559ae6-9564-4f99-9409-1321f42690a7 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=alcobendas | subsrv=/inmotica | msg=error batchUpdate{​​​​​​​"name":"BadRequest","message":"empty entities vector","correlator":"377b0811-b0c9-4230-9c7c-c98ed4416a59; node=jKUzSyLEg; perseocep=18"}​​​​​​​
time=2021-01-29T12:53:08.889Z | lvl=ERROR | corr=377b0811-b0c9-4230-9c7c-c98ed4416a59; node=jKUzSyLEg; perseocep=18 | trans=01559ae6-9564-4f99-9409-1321f42690a7 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=alcobendas | subsrv=/inmotica | msg=ALARM-ON [ORION] {​​​​​​​"name":"BadRequest","message":"empty entities vector","correlator":"377b0811-b0c9-4230-9c7c-c98ed4416a59; node=jKUzSyLEg; perseocep=18"}​​​​​​​

It tries to query CB (multiplie action) but no entity is returned and rule brokes

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/487
