### ISSUE TITLE
Using copy or git clone on dockerfile

### ISSUE THREAD

**Issue by IvanHdzC** [telefonicaid/perseo-fe#498]
Nowadays the Dockerfile runs a git clone to get sources from where the image will be built on.

The advantages of this are:

- Upgrades on Dockerfile can fully apply backwards. This means that any change on the current Dockerfile can be applied to any previous version of Perseo fe. Since it pulls sources from git on any workflow.
- Isolated builds from any base images. Using docker building args you can setup any base image and sources to run any test or use any setup without changing the Dockerfile.

By the other hand, the disadvantages can be:

- Not building from current context. Whenever you build the image it has to be from a remote public repository. If you want to build your current workflow it has to be by pulling it from a remote repo, not from local workflow. Also this means that it has to be a public repo.
- Aditional steps added. The build stage is distro dependant (debian), and it downloads sources from the internet. This means that in the case you run this image with restricted internet access, it has to have access to github. Perhaps whenever you change the base image you must make shure all git clone process works fine.

An alternative can be using COPY instead of the current solution.

Using COPY would solve both mentioned issues. And it has the advantages of using native docker functions. However using Copy would have the following disadvantages:

- Upgrades on Dockerfile have not backward compatibility.
- Change of build context on the docker build hook.

Aditionally. Changes on versions (of sources or base image) have to be done on the current workflow on the Dockerfile, since the image will be built from the current context. so you have to run: 

```bash
git checkout release/1.7.0
cd .. # To change to the root of the perseo repository. Assuming you are on the docker path of this repo.
docker image build -t perseo -f docker/Dockerfile . # In the case you are on a fork, then you should know where the Dockerfile is located
```

**Comment by fgalan** [comment]
Raised in PR https://github.com/telefonicaid/perseo-fe/pull/495

This issue is created in Perseo FE repo (as the cited PR is in that repo) but it impacts any other repo using the same approach (i.e. IOTAs, etc.).

**Comment by AlvaroVega** [comment]
Currently Dockerfile of perseo-fe is implemented as others compontents (like iotagents) and uses by default git branch but allow copy for local develpment:

https://github.com/telefonicaid/perseo-fe/blob/4940ba7fd63985810b04f821f796c0ea42a71a66/docker/Dockerfile#L55-L61
