### ISSUE TITLE
Perseo does not notify DateTime values to core for NGSIv2

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#503]
Perseo makes a special treatment for DateTime notified attributes. It extracts some values to be available for perseo-core but it forgets to send the value itself.

This behaviour can be reproduced for any rule that receives a DateTime attribute.

It's failing for normalized subscriptions. Legacy subscriptions is working.

An example of rule to test it (a simple rule) could be the following:

```json
{
            "name": "prueba_absurda",
            "text": "SELECT *, cast(cast(TimeInstant?, String), date, dateformat: 'iso').format(\"yyyy-MM-dd'T'HH:mm:ss.SSSX\") as currenttime FROM iotEvent",
            "action": {
                "type": "update",
                "parameters": {
                    "attributes": [
                        {
                            "name": "dateCalculatedEmptyings",
                            "value": "${currenttime}",
                            "type": "DateTime"
                        }
                    ]
                }
            }
        }
```
In this case TimeInstant is a DateTime attribute and perseo-fe sends to perseo-core the following notification:

```json
{
  "noticeId": "89866510-830a-11eb-9506-e110bf4f629f",
  "noticeTS": 1615536684513,
  "id": "coche1",
  "type": "coche",
  "isPattern": false,
  "subservice": "/pruebas",
  "service": "alcobendas",
  "TimeInstant__type": "DateTime",
  "TimeInstant__ts": 1615536684000,
  "TimeInstant__day": 12,
  "TimeInstant__month": 3,
  "TimeInstant__year": 2021,
  "TimeInstant__hour": 8,
  "TimeInstant__minute": 11,
  "TimeInstant__second": 24,
  "TimeInstant__millisecond": 0,
  "TimeInstant__dayUTC": 12,
  "TimeInstant__monthUTC": 3,
  "TimeInstant__yearUTC": 2021,
  "TimeInstant__hourUTC": 8,
  "TimeInstant__minuteUTC": 11,
  "TimeInstant__secondUTC": 24,
  "TimeInstant__millisecondUTC": 0,
  "noSignalEnable__type": "Text",
  "noSignalEnable": "ok",
  "vel__type": "Number",
  "vel": 34,
  "stripped": {
    "id": "coche1",
    "type": "coche",
    "TimeInstant": {
      "type": "DateTime",
      "value": "2021-03-12T08:11:24.000Z",
      "metadata": {}
    },
    "noSignalEnable": {
      "type": "Text",
      "value": "ok",
      "metadata": {}
    },
    "vel": {
      "type": "Number",
      "value": 34,
      "metadata": {}
    }
  }
}
````
Note that TimeInstant value is missing.

The value should be added in this function https://github.com/telefonicaid/perseo-fe/blob/master/lib/models/notices.js#L264

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/502

Can this issue be closed or anything else is pending?

**Comment by AlvaroVega** [comment]
time=2021-04-14T08:09:01.471Z | lvl=DEBUG | corr=aba88c60-9cf8-11eb-a11b-0242ac110010; cbnotif=1; node=gALyTtUFO; perseocep=19 | trans=81c738ad-c66a-428e-8b0f-a05a13f5fca2 | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=smartcity | subsrv=/ | msg=executing axn task {"action":{"type":"email","template":"IoT message${type}${id}","parameters":{"to":"pepe@blalba","from":"pepe@blalba","subject":"IoT message"},"index":0},"event":{"ev":{"TimeInstant__second":37,"MiOtrocommand_info":" ","TimeInstant__hour":8,"MiOtrocommand_status":"UNKNOWN","TimeInstant__day":14,"stripped":{"MiOtrocommand_status":{"type":"commandStatus","value":"UNKNOWN","metadata":{}},"id":"test","type":"thing","MiOtrocommand_info":{"type":"commandResult","value":" ","metadata":{}},"TimeInstant":{"type":"DateTime","value":"2021-04-14T08:08:37.605Z","metadata":{}}},"type":"thing","isPattern":false,"TimeInstant__type":"DateTime","TimeInstant__millisecond":605,"subservice":"/","TimeInstant__monthUTC":4,"MiOtrocommand_info__type":"commandResult","TimeInstant__year":2021,"TimeInstant__yearUTC":2021,"TimeInstant__month":4,"id":"test","MiOtrocommand_status__type":"commandStatus","TimeInstant__minute":8,"TimeInstant__millisecondUTC":605,"noticeTS":1618387741117,"TimeInstant__hourUTC":8,"noticeId":"abafa6d0-9cf8-11eb-8b36-b14e150bb069","TimeInstant__ts":1618387717605,"service":"smartcity","TimeInstant__minuteUTC":8,"TimeInstant__secondUTC":37,**"TimeInstant":"2021-04-14T08:08:37.605Z"**,"TimeInstant__dayUTC":14},"ruleName":"emailtest","subservice":"/","service":"smartcity","fiwarePerseoContext":{"path":"/actions/do","op":"/actions/do","comp":"perseo-fe","trans":"81c738ad-c66a-428e-8b0f-a05a13f5fca2","corr":"aba88c60-9cf8-11eb-a11b-0242ac110010; cbnotif=1; node=gALyTtUFO; perseocep=19","srv":"smartcity","subsrv":"/"},"TimeInstant__second":37,"MiOtrocommand_info":" ","TimeInstant__hour":8,"MiOtrocommand_status":"UNKNOWN","TimeInstant__day":14,"stripped":{"MiOtrocommand_status":{"type":"commandStatus","value":"UNKNOWN","metadata":{}},"id":"test","type":"thing","MiOtrocommand_info":{"type":"commandResult","value":" ","metadata":{}},"TimeInstant":{"type":"DateTime","value":"2021-04-14T08:08:37.605Z","metadata":{}}},"type":"thing","isPattern":false,"TimeInstant__type":"DateTime","TimeInstant__millisecond":605,"TimeInstant__monthUTC":4,"MiOtrocommand_info__type":"commandResult","TimeInstant__year":2021,"TimeInstant__yearUTC":2021,"TimeInstant__month":4,"id":"test","MiOtrocommand_status__type":"commandStatus","TimeInstant__minute":8,"TimeInstant__millisecondUTC":605,"noticeTS":1618387741117,"TimeInstant__hourUTC":8,"noticeId":"abafa6d0-9cf8-11eb-8b36-b14e150bb069","TimeInstant__ts":1618387717605,"TimeInstant__minuteUTC":8,"TimeInstant__secondUTC":37,"TimeInstant":"2021-04-14T08:08:37.605Z","TimeInstant__dayUTC":14},"context":{"path":"/actions/do","op":"/actions/do","comp":"perseo-fe","trans":"81c738ad-c66a-428e-8b0f-a05a13f5fca2","corr":"aba88c60-9cf8-11eb-a11b-0242ac110010; cbnotif=1; node=gALyTtUFO; perseocep=19","srv":"smartcity","subsrv":"/"}}
