### ISSUE TITLE
Perseo does not expand location (geo:point) values to core for NGSIv2

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#504]
location fields in event https://github.com/telefonicaid/perseo-fe/blob/master/documentation/plain_rules.md#location-fields

like does in ngsiv1
https://github.com/telefonicaid/perseo-fe/blob/83d3949ea5916839ad8cdf04787e47d460095af3/lib/models/notices.js#L184-L193

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/506
