### ISSUE TITLE
Perseo-fe does not accept geo:json in filter action

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#512]
It could be necesary to make a wrapping on the ngsijs library in order to transform a geo:json value to a context broker geometry/coords param.

**Comment by AlvaroVega** [comment]
I guess this kind of filters are working:

{
    "name": "blood_rule_update",
    "text": "select *,\"blood_rule_update\" as ruleName, *, ev.BloodPressure? as Pressure from pattern [every ev=iotEvent(BloodPressure? > 1.5 and type=\"BloodMeter\")]",
    "action": {
        "type": "update",
        "parameters": {
            "filter": {
                "type": "SensorMetter",
                "q": "status:on",
                "geometry":"point",
                "georel":"near;maxDistance:1000",
                "coords":"-80.190,25.774"
            },
            "version": 2,
            "attributes": [
                {
                    "name": "pressure",
                    "type": "Number",
                    "value": "${Pressure}"
                }
            ]
        }
    }
}

@fgalan is there any way of translate a geo:json to something like
                "geometry":"point",
                "georel":"near;maxDistance:1000",
                "coords":"-80.190,25.774"
?

**Comment by fgalan** [comment]
> @fgalan is there any way of translate a geo:json to something like
> "geometry":"point",
> "georel":"near;maxDistance:1000",
> "coords":"-80.190,25.774"
> ?

I may be wrong, but as far as I know, GeoJSON is not capable of describing circles or [annulus](https://en.wikipedia.org/wiki/Annulus_(mathematics)). See for intance the answerst to this SOF question: https://stackoverflow.com/questions/16942697/geojson-circles-supported-or-not

**Comment by mrutid** [comment]
The proper CEP action may be the one transpiring geo:json to CB polygon. Circles or ANUlus are not important... polygons and coropletes are.

**Comment by mrutid** [comment]
Now action.parameters to filter entities inside a polygon looks like this:
```
{
"parameters": {
"actionType": "UPDATE",
"filter": {
"type": "Streetlight",
"**georel**": "coveredBy",
"**geometry**": "polygon",
"**coords**":"40.540066392436586,-3.6341786384582515;40.540066392436586,-3.629125356674194;40.54137907639843,-3.629125356674194;40.54137907639843,-3.6341786384582```
515;40.540066392436586,-3.6341786384582515"
}
}
```
the Idea is to support an action like this:
```
{
"parameters": {
"actionType": "UPDATE",
"filter": {
"type": "Streetlight",
"**georel**": "coveredBy",
"**geojsonpolygon**": {
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {},
      "geometry": {
        "type": "Polygon",
        "coordinates": [[ [ 9.84375, 54.36775852406841 ], [ -4.921875, 42.032974332441405 ], [ 34.80468749999999, 40.713955826286046 ], [ 29.53125, 53.54030739150022 ], [ 9.84375, 54.36775852406841 ] ] ]
      }
    }
  ]
}
}
```

Just by transforming into the previous NGSI polygon definition.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/513 has been merged.

Should this issue be closed? Or is there anything pending?
