### ISSUE TITLE
Improve SMS action in order to include SMPP server configuration.

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#517]
SMPP configuration should be avaliable at SMS action, and not only at config file level:

/**
 * SMPP endpoint options
 */
config.smpp = {
    host: '',
    port: '',
    systemid: '',
    password: '',
    from: '346666666',
    enabled: false
};

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/518
