### ISSUE TITLE
initial notification in ngsiv2 is procesed as Bad HTTP notification

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#527]
When CB is notifying in ngsiv2 several entities in the same fiware-servicepath (like /)

```
time=2021-05-21T09:02:02.557Z | lvl=INFO | corr=353ab12e-ba13-11eb-a5eb-0242ac110011; node=Y6jsj505U; perseocep=206 | trans=9b50a50e-97f2-4748-9d3a-a754be349a5e | op=/notices | path=/notices | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.17 | msg=sending response: 400 {"error":"Number of servicepath items does not match ContextResponses(1,2)","data":null}

```

https://github.com/telefonicaid/perseo-fe/blob/1f3c70c94bccb50b74d9c2e827fa9ffb577f0491/lib/models/notices.js#L382-L383

similar to https://github.com/telefonicaid/fiware-cygnus/issues/2042

probably no needed due to https://github.com/telefonicaid/perseo-fe/issues/526

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/528
