### ISSUE TITLE
Add new fields to rules: description and misc

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#532]
Add two new fields to rules, to include a description and miscelaneous informacion

**Comment by AlvaroVega** [comment]
Currently this is the code that checks if a rule is valid, checking all needed fields like name, actions, text...

But there is nothing that prevents to add others fields in json rule, like `description` or `misc`, which now will be optional.

https://github.com/telefonicaid/perseo-fe/blob/cc76f6634ebdbdaf3c8a5cb46d7892c7eeec6069/lib/models/rules.js#L47-L74

**Comment by fgalan** [comment]
> Currently this is the code that checks if a rule is valid, checking all needed fields like name, actions, text...
> 
> But there is nothing that prevents to add others fields in json rule, like `description` or `misc`, which now will be optional.

Do you mean that any field could be added/retrieved, i.e. `"patata": "..."`?

In that case, maybe this issue can be solved just with documenting the new fields in the corresponding .md files.

**Comment by AlvaroVega** [comment]
> Do you mean that any field could be added/retrieved, i.e. `"patata": "..."`?

Yes, `patata` is welcome!

**Comment by fgalan** [comment]
Fixed (by documenting) in PR https://github.com/telefonicaid/perseo-fe/pull/534
