### ISSUE TITLE
Wrong detection of notification loops (due to new CB correlator management).

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#536]
Once in a loop we are generating this kind of correlators (due to new corr mangement at CB).

correlator":"b12cbfc2-e09f-11eb-9d80-0242ac110013; cbnotif=1; node=qVEyXINDl; perseocep=85962; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; cbnotif=1; 

https://github.com/telefonicaid/perseo-fe/blob/1f3c70c94bccb50b74d9c2e827fa9ffb577f0491/lib/routes/actionsController.js#L41

At PERSEO-FE we are using correlator to make loop detections:

 correlator = req.headers[constants.CORRELATOR_HEADER]

Now it's not valid. We should remove "cbnotif=" atoms anddo the match just with "static part" os the correlator:

¿b12cbfc2-e09f-11eb-9d80-0242ac110013?
¿b12cbfc2-e09f-11eb-9d80-0242ac110013; node=qVEyXINDl; perseocep=85962?

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/perseo-fe/pull/457

**Comment by fgalan** [comment]
PR #537 

Should this issue be closed once that PR has been merged?
