### ISSUE TITLE
bad update rule in perseo-core is returned as 500 error by perseo-fe

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#539]
A bad rule update:

perseo-fe log:

time=2021-07-16T08:54:10.740Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE) {"ok":1}
time=2021-07-16T08:54:10.742Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE_ORION) {"ok":1}
time=2021-07-16T08:54:15.743Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE) {"ok":1}
time=2021-07-16T08:54:15.744Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE_ORION) {"ok":1}
time=2021-07-16T08:54:19.173Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=incoming request {"method":"PUT","url":"/rules/rule2name","headers":{"host":"iot-pep-perseo-fe:1026","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","accept":"application/json","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","content-type":"application/json;charset=utf-8","x-auth-token":"gAAAAABg8UWYhL4-IX1DLwsRIbJEjGFInpfOE2nHAtPX3JpC8x9OLkB51p-yUwCf4tFKgE0q5iPxP_bbJJglak_mvRMUzMK2hBPhtxkGu7luU06p_ovKS1evYGcsvxvzprbu3jlUpezys8GMwr6XJPz_x0aMOvwBP_Nu21R49tcJTHsv4DRh_rU","fiware-service":"smartcity","fiware-servicepath":"/","origin":"https://localhost","referer":"https://localhost/rules/rule2name","cookie":"hblid=L6VbkwGcvkKzdrZC3m39N0N1b0W0WB1O; olfsk=olfsk7435810787909288; userObligationsViewed=true; authToken=%7B%22XAuthToken%22%3A%22gAAAAABg8UWYhL4-IX1DLwsRIbJEjGFInpfOE2nHAtPX3JpC8x9OLkB51p-yUwCf4tFKgE0q5iPxP_bbJJglak_mvRMUzMK2hBPhtxkGu7luU06p_ovKS1evYGcsvxvzprbu3jlUpezys8GMwr6XJPz_x0aMOvwBP_Nu21R49tcJTHsv4DRh_rU%22%2C%22domainName%22%3A%22smartcity%22%2C%22projectName%22%3Anull%2C%22extras%22%3A%7B%22password_creation_time%22%3A%222020-01-01T08%3A33%3A31Z%22%2C%22sndfa_email%22%3Afalse%2C%22last_login_attempt_time%22%3A%222021-07-14T07%3A15%3A48.000000%22%2C%22pwd_user_in_blacklist%22%3Atrue%2C%22password_expiration_time%22%3A%222020-12-31T08%3A33%3A31Z%22%7D%7D","x-forwarded-for":"172.17.0.24","content-length":"401"},"body":{"name":"rule2name","description":"mi rule 2 description3","misc":"miscelanea info for rule 4","text":"select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]","VR":"","action":{"type":"update","parameters":{"id":"${id}_example","version":2,"attributes":[{"name":"pressure","type":"Number","value":"${Pressure}"}]}},"nosignal":"","subservice":"/","service":"smartcity"},"subservice":"/","service":"smartcity"}
time=2021-07-16T08:54:19.173Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=putting rule {"name":"rule2name","description":"mi rule 2 description3","misc":"miscelanea info for rule 4","text":"select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]","VR":"","action":{"type":"update","parameters":{"id":"${id}_example","version":2,"attributes":[{"name":"pressure","type":"Number","value":"${Pressure}"}]}},"nosignal":"","subservice":"/","service":"smartcity"}
time=2021-07-16T08:54:19.173Z | lvl=DEBUG | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=validRule() - Default else clause
time=2021-07-16T08:54:19.173Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=making del to http://iot-perseo-core:8080/perseo-core/rules/rule2name@smartcity/
time=2021-07-16T08:54:19.179Z | lvl=DEBUG | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=del to http://iot-perseo-core:8080/perseo-core/rules/rule2name@smartcity/ returns {"code":200,"body":"{\"name\":\"rule2name@smartcity/\",\"timeLastStateChange\":1626425659128,\"text\":\"context ctxt$smartcity$ select *,'rule2name' as ruleName from pattern [every ev=iotEvent(type='SensorMetter')]\",\"state\":\"DESTROYED\"}"}
time=2021-07-16T08:54:19.179Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=done del to http://iot-perseo-core:8080/perseo-core/rules/rule2name@smartcity/
time=2021-07-16T08:54:19.179Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=making post to http://iot-perseo-core:8080/perseo-core/rules
time=2021-07-16T08:54:19.183Z | lvl=DEBUG | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=post to http://iot-perseo-core:8080/perseo-core/rules returns {"code":200,"body":{"name":"ctxt$smartcity$","timeLastStateChange":1626418978828,"text":"create context ctxt$smartcity$ partition by service from iotEvent(service=\"smartcity\" and subservice=\"/\")","state":"STARTED"}}
time=2021-07-16T08:54:19.183Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=done post to http://iot-perseo-core:8080/perseo-core/rules
time=2021-07-16T08:54:19.183Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=making post to http://iot-perseo-core:8080/perseo-core/rules
time=2021-07-16T08:54:19.188Z | lvl=DEBUG | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=post to http://iot-perseo-core:8080/perseo-core/rules returns {"code":400,"body":{"error":"Incorrect syntax near 'ev' expecting a right angle bracket ']' but found an identifier at line 1 column 78, please check the from clause [context ctxt$smartcity$ select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]]"}}
time=2021-07-16T08:54:19.188Z | lvl=ERROR | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=[object Object] error post to http://iot-perseo-core:8080/perseo-core/rules (Incorrect syntax near 'ev' expecting a right angle bracket ']' but found an identifier at line 1 column 78, please check the from clause [context ctxt$smartcity$ select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]])
time=2021-07-16T08:54:19.189Z | lvl=ERROR | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=invalid key for metrics undefined
time=2021-07-16T08:54:19.189Z | lvl=DEBUG | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=putRules res [{"code":200,"body":{"name":"ctxt$smartcity$","timeLastStateChange":1626418978828,"text":"create context ctxt$smartcity$ partition by service from iotEvent(service=\"smartcity\" and subservice=\"/\")","state":"STARTED"}},{"code":400,"body":{"error":"Incorrect syntax near 'ev' expecting a right angle bracket ']' but found an identifier at line 1 column 78, please check the from clause [context ctxt$smartcity$ select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]]"}}]
time=2021-07-16T08:54:19.189Z | lvl=INFO | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=sending response: 500 {"error":"error post to http://iot-perseo-core:8080/perseo-core/rules (Incorrect syntax near 'ev' expecting a right angle bracket ']' but found an identifier at line 1 column 78, please check the from clause [context ctxt$smartcity$ select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]])","data":null}
time=2021-07-16T08:54:19.189Z | lvl=DEBUG | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=56ff5f22-12f4-48f7-a98d-ed9fc638d845 | op=/rules/rule2name | path=/rules/rule2name | comp=perseo-fe | srv=smartcity | subsrv=/ | from=::ffff:172.17.0.16 | msg=response-time: 17 statusCode: 500
time=2021-07-16T08:54:20.743Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE) {"ok":1}
time=2021-07-16T08:54:20.745Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE_ORION) {"ok":1}
time=2021-07-16T08:54:25.748Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE) {"ok":1}
time=2021-07-16T08:54:25.749Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE_ORION) {"ok":1}
time=2021-07-16T08:54:30.747Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE) {"ok":1}
time=2021-07-16T08:54:30.747Z | lvl=DEBUG | corr=n/a | trans=n/a | op=n/a | msg=ping (DATABASE_ORION) {"ok":1}

perseo-core log

time=2021-07-16T08:54:19.176Z | lvl=INFO | from=::ffff:172.17.0.16 | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=a82240ab-89e7-4d91-a57b-0bbce9a0b028 | srv=smartcity | subsrv=/ | op=doDelete | comp=perseo-core | msg=delete rule /rule2name@smartcity/
time=2021-07-16T08:54:19.177Z | lvl=INFO | from=::ffff:172.17.0.16 | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=a82240ab-89e7-4d91-a57b-0bbce9a0b028 | srv=smartcity | subsrv=/ | op=removeTimeRule | comp=perseo-core | msg=Removing timerule: rule2name@smartcity/
time=2021-07-16T08:54:19.182Z | lvl=INFO | from=::ffff:172.17.0.16 | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=5dbb548d-0018-42b7-be40-3bcfa6c4e4ce | srv=smartcity | subsrv=/ | op=make | comp=perseo-core | msg=post rule: ctxt$smartcity$
time=2021-07-16T08:54:19.186Z | lvl=INFO | from=::ffff:172.17.0.16 | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=395386c4-5a0b-4cbf-8c4f-ab72a01f316d | srv=smartcity | subsrv=/ | op=make | comp=perseo-core | msg=post rule: rule2name@smartcity/
time=2021-07-16T08:54:19.187Z | lvl=ERROR | from=::ffff:172.17.0.16 | corr=56ff5f22-12f4-48f7-a98d-ed9fc638d845; node=mTbBmM8p7; perseocep=238 | trans=395386c4-5a0b-4cbf-8c4f-ab72a01f316d | srv=smartcity | subsrv=/ | op=make | comp=perseo-core | msg=creating statement com.espertech.esper.client.EPStatementSyntaxException: Incorrect syntax near 'ev' expecting a right angle bracket ']' but found an identifier at line 1 column 78, please check the from clause [context ctxt$smartcity$ select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]]

pep-perseo-fe:

time=2021-07-16T08:54:19.167Z | lvl=DEBUG | corr=1e05c171-d34e-4b60-909a-74df41ce2310 | trans=1e05c171-d34e-4b60-909a-74df41ce2310 | op=/rules/rule2name | from=n/a | srv=smartcity | subsrv=/ | msg=Request access accepted | comp=PEPperseo
time=2021-07-16T08:54:19.168Z | lvl=DEBUG | corr=1e05c171-d34e-4b60-909a-74df41ce2310 | trans=1e05c171-d34e-4b60-909a-74df41ce2310 | op=/rules/rule2name | from=n/a | srv=smartcity | subsrv=/ | msg=Forwarding request:

{"uri":"http://iot-perseo-fe:9090/rules/rule2name","qs":{},"method":"PUT","headers":{"host":"iot-pep-perseo-fe:1026","connection":"close","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0","accept":"application/json","accept-language":"en-US,en;q=0.5","accept-encoding":"gzip, deflate, br","content-type":"application/json;charset=utf-8","x-auth-token":"gAAAAABg8UWYhL4-IX1DLwsRIbJEjGFInpfOE2nHAtPX3JpC8x9OLkB51p-yUwCf4tFKgE0q5iPxP_bbJJglak_mvRMUzMK2hBPhtxkGu7luU06p_ovKS1evYGcsvxvzprbu3jlUpezys8GMwr6XJPz_x0aMOvwBP_Nu21R49tcJTHsv4DRh_rU","fiware-service":"smartcity","fiware-servicepath":"/","origin":"https://localhost","referer":"https://localhost/rules/rule2name","cookie":"hblid=L6VbkwGcvkKzdrZC3m39N0N1b0W0WB1O; olfsk=olfsk7435810787909288; userObligationsViewed=true; authToken=%7B%22XAuthToken%22%3A%22gAAAAABg8UWYhL4-IX1DLwsRIbJEjGFInpfOE2nHAtPX3JpC8x9OLkB51p-yUwCf4tFKgE0q5iPxP_bbJJglak_mvRMUzMK2hBPhtxkGu7luU06p_ovKS1evYGcsvxvzprbu3jlUpezys8GMwr6XJPz_x0aMOvwBP_Nu21R49tcJTHsv4DRh_rU%22%2C%22domainName%22%3A%22smartcity%22%2C%22projectName%22%3Anull%2C%22extras%22%3A%7B%22password_creation_time%22%3A%222020-01-01T08%3A33%3A31Z%22%2C%22sndfa_email%22%3Afalse%2C%22last_login_attempt_time%22%3A%222021-07-14T07%3A15%3A48.000000%22%2C%22pwd_user_in_blacklist%22%3Atrue%2C%22password_expiration_time%22%3A%222020-12-31T08%3A33%3A31Z%22%7D%7D","x-forwarded-for":"172.17.0.24"},"body":"{\"name\":\"rule2name\",\"description\":\"mi rule 2 description3\",\"misc\":\"miscelanea info for rule 4\",\"text\":\"select *,'rule2name' as ruleName from pattern [everya ev=iotEvent(type='SensorMetter')]\",\"VR\":\"\",\"action\":{\"type\":\"update\",\"parameters\":{\"id\":\"${id}_example\",\"version\":2,\"attributes\":[{\"name\":\"pressure\",\"type\":\"Number\",\"value\":\"${Pressure}\"}]}},\"nosignal\":\"\",\"subservice\":\"/\",\"service\":\"smartcity\"}"}
 | comp=PEPperseo
time=2021-07-16T08:54:19.191Z | lvl=DEBUG | corr=1e05c171-d34e-4b60-909a-74df41ce2310 | trans=1e05c171-d34e-4b60-909a-74df41ce2310 | op=/rules/rule2name | from=n/a | srv=smartcity | subsrv=/ | msg=response-time: 578 statusCode: 500 | comp=PEPperseo

**Comment by AlvaroVega** [comment]
And 40X error from perseo-core is always returned as 500 error:

https://github.com/telefonicaid/perseo-fe/blob/b317e01fc9ed12001e8ee066e504c3fb0868a481/lib/myutils.js#L184-L195

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/540
