### ISSUE TITLE
No signal rules based in NGSIv2 API instead of MongoDB direct access

### ISSUE THREAD

**Issue by fgalan** [telefonicaid/perseo-fe#549]
Currently, the no-signal rules are based in direct queries to the Orion DB at MongoDB. It would be better to do it using the NGSIv2 API using a query filter based in dateModified virtual attribute.

Example of non signal rule:
```
{
    "name": "check_temp_no_signal",
    "nosignal": {
        "checkInterval": "1",
        "attribute": "temperature",
        "reportInterval": "5",
        "id": null,
        "idRegexp": "^value.*",
        "type": null
    },
   "action": {
        "type": "update",
        "parameters": {
            "filter": {
                "type": "StreetlightZone",
                "q": "dateModified<${limite}"
            },
            "version": 2,
            "attributes": [
                {
                    "name": "aux",
                    "type": "Text",
                    "value": "Not Modified"
                }
            ]
        }
    }

}
```

**Comment by manucarrace** [comment]
This could be a rule with similar behaviour.

```json
{
    "name": "prueba_ausencia",
    "text": "select *, current_timestamp.minus(5 min).format(\"yyyy-MM-dd'T'HH:mm:ss.SSSX\") as limite, current_timestamp().format(\"yyyy-MM-dd'T'HH:mm:ss.SSSX\") as time FROM PATTERN [EVERY timer:interval(1 min)]",
	"action": {
        "type": "update",
        "parameters": {
            "filter": {
                "type": "StreetlightZone",
                "q": "dateModified<${limite}"
            },
            "version": 2,
            "attributes": [
                {
                    "name": "aux",
                    "type": "Text",
                    "value": "Not Modified"
                }
            ]
        }
    }
}
```

Where: 
- checkInterval: 1 min
- reportInterval: 5 min

Please, note that the rule is updating the non-updated entities when the action is executed, so the entity changes and dateModified is updated now! 

This behaviour could be acceptable in some scenarios. The entity is marked as "Not modified" and is not marked again until the next reportInterval.

**Comment by AlvaroVega** [comment]
It must be a flag option

**Comment by AlvaroVega** [comment]
For achieve this issue we can use ngsijs query like performed by: 

https://github.com/telefonicaid/perseo-fe/blob/07097ca5776b281def802eb8fa726b7e73861ab1/lib/models/updateAction.js#L437

**Comment by AlvaroVega** [comment]
Regarding nosignal documentation: 


No signal conditions

The no signal condition is specified in the nosignal configuration element, which is an object with the following fields:

    checkInterval: mandatory, time in minutes for checking the attribute. Min value is 0.5 and max is 35791, other values are truncated to them (a warning log message is generated if such truncation occurs)
    attribute: mandatory, attribute for watch
    reportInterval: mandatory, time in seconds to see an entity as silent (in other words, how much time has to pass since last entity update to consider that entity is in "no signal" situation so the rule is triggered)
    id or idRegexp: mandatory (but not both at the same time), ID or regular expression of the entity to watch
    type: optional, type of entities to watch

Is recommended to set checkInterval at least double of reportInterval. Howeer, note that a very demanding value of checkInterval could impact on performance.
Non signal actions

Along with all the entity attributes, the following virtual attributes are available to be used in non signal template actions:

    service: service of rule
    subservice: subservice of rule
    ruleName: name of the rule
    reportInterval: time to see an entity as silent (in other words, how much time has to pass since last entity update to consider that entity is in "no signal" situation so the rule is triggered)
    id: entity id
    type: entity type
    internalCurrentTime: current time
    lastTime: lastTime rule was executed as well as all entity attributes

**Comment by AlvaroVega** [comment]
Is there any way using NGSIv2 API of retrieve one or several entities identified by id, type, serv and subserv which some attribute was not modified during some period of time?

**Comment by fgalan** [comment]
...being `T_3` a bash var in this example, created this way:

```
T_3=$(TZ=GMT date +"%Y-%m-%dT%H:%M:%S.000Z")
```
