### ISSUE TITLE
error with previous rules when perseo-fe 1.18.0

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#556]
node:1) [MONGODB DRIVER] Warning: Current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:1) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.
time=2021-09-30T12:00:13.648Z | lvl=INFO | corr=n/a | trans=n/a | op=initialRefresh | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=rulesStore.FindAll [{"_id":"5e565b138e62635898eb0263","name":"rule_PM10_dia","text":"SELECT \"rule_PM10_dia\" as ruleName, *, case when window(* [...]
time=2021-09-30T12:00:14.009Z | lvl=INFO | corr=n/a | trans=n/a | op=initialRefresh | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=making put to http://iot-perseo-core:8080/perseo-core/rules
time=2021-09-30T12:00:21.835Z | lvl=ERROR | corr=n/a | trans=n/a | op=initialRefresh | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=[object Object] error put to http://iot-perseo-core:8080/perseo-core/rules (Unexpected end-of-input near end-of-input ('SELECT' is a reserved keyword) at line 1 column 46, please check the select clause [context ctxt$alcoy$eficienciaenergetica SELECT])
time=2021-09-30T12:00:21.835Z | lvl=ERROR | corr=n/a | trans=n/a | op=initialRefresh | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=[object Object] error put to http://iot-perseo-core:8080/perseo-core/rules (Unexpected end-of-input near end-of-input ('SELECT' is a reserved keyword) at line 1 column 46, please check the select clause [context ctxt$alcoy$eficienciaenergetica SELECT])
time=2021-09-30T12:00:21.836Z | lvl=INFO | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=starting perseo
time=2021-09-30T12:00:21.836Z | lvl=FATAL | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=error put to http://iot-perseo-core:8080/perseo-core/rules (Unexpected end-of-input near end-of-input ('SELECT' is a reserved keyword) at line 1 column 46, please check the select clause [context ctxt$alcoy$eficienciaenergetica SELECT])

**Comment by AlvaroVega** [comment]
some * whre missed. God text rule is:

SELECT "rule_PM10_dia" as ruleName, * , case when window(*,filter:cast(cast(PM10_value?,String),float) > cast(cast(PM10_preaviso?,String),float) and cast(cast(PM10_value?,String),float) <= cast(cast(PM10_aviso?,String),float)) is not null then Arrays.toString(window(cast(refPointOfInterest?,string) || ' - Valor Actual : ' || cast(PM10_value?,string) || ' - Valor Previo: ' || cast(PM10_value_prev?,string),filter:cast(cast(PM10_value?,String),float) > cast(cast(PM10_preaviso?,String),float) and cast(cast(PM10_value?,String),float) <= cast(cast(PM10_aviso?,String),float))) else 'Ninguna' end as preaviso, case when window(*,filter:cast(cast(PM10_value?,String),float) > cast(cast(PM10_aviso?,String),float)) is not null then Arrays.toString(window(cast(refPointOfInterest?,string) || ' - Valor Actual : ' || cast(PM10_value?,string) || ' - Valor Previo: ' || cast(PM10_value_prev?,string),filter:cast(cast(PM10_value?,String),float) > cast(cast(PM10_aviso?,String),float))) else 'Ninguna' end as aviso from iotEvent.std:unique(id?).win:time(2 days) where cast(cast(PM10_value?,String),float) > cast(cast(PM10_preaviso?,String),float) and cast(cast(PM10_value_prev?,String),float) > cast(cast(PM10_preaviso?,String),float) and cast(id?,string) like '%_24h' HAVING count(*) > 1

**Comment by AlvaroVega** [comment]
Apparently rules are fine in mongo, but when edit some one we can se CR and LF characters:

![Screenshot from 2021-10-05 08-21-11](https://user-images.githubusercontent.com/983422/135970967-f4d7cbd3-2dcf-4262-b5f2-1b4f429e0049.png)

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/563 fixes this.
