### ISSUE TITLE
Error from Perseo-core is stopping perseo-fe

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#557]
i.e. when a bad sintax rule is already in db and both components restarts:

https://github.com/telefonicaid/perseo-fe/issues/556#issue-1012119036

Any error propagated to this point
https://github.com/telefonicaid/perseo-fe/blob/f8bc5d77203d177efc7c0070e120d627498a7853/bin/perseo#L233-L235
results in a perseo-fe stop with a fatal log

**Comment by AlvaroVega** [comment]
time=2021-09-30T14:34:40.535Z | lvl=DEBUG | corr=n/a | trans=n/a | op=initialRefresh | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=put to http://iot-perseo-core:8080/perseo-core/rules returns {"code":400,"body":{"error":"Unexpected end-of-input near end-of-input ('SELECT' is a reserved keyword) at line 1 column 39, please check the select clause [context ctxt$dip_castellon$riego SELECT]"}}
time=2021-09-30T14:34:40.535Z | lvl=ERROR | corr=n/a | trans=n/a | op=initialRefresh | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=[object Object] error put to http://iot-perseo-core:8080/perseo-core/rules (Unexpected end-of-input near end-of-input ('SELECT' is a reserved keyword) at line 1 column 39, please check the select clause [context ctxt$dip_castellon$riego SELECT])
time=2021-09-30T14:34:40.535Z | lvl=ERROR | corr=n/a | trans=n/a | op=initialRefresh | comp=perseo-fe | srv=n/a | subsrv=n/a | msg=[object Object] error put to http://iot-perseo-core:8080/perseo-core/rules (Unexpected end-of-input near end-of-input ('SELECT' is a reserved keyword) at line 1 column 39, please check the select clause [context ctxt$dip_castellon$riego SELECT])

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/558

Maybe we leave this issue opened, while we check if it effective solves the problem.

**Comment by AlvaroVega** [comment]
Failiure is still in https://github.com/telefonicaid/perseo-fe/blob/master/lib/models/rules.js#L192

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/562
