### ISSUE TITLE
location is expanded in all attribute event when is found

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#560]
time=2021-09-30T15:28:16.229Z | lvl=INFO | from=::ffff:172.17.0.18 | corr=085d0988-2203-11ec-bd1a-0242ac110012; cbnotif=1; node=gIyjPsV6Q; perseocep=266 | trans=7330f602-80e3-415a-a846-c6975460b39e | srv=alcobendas | subsrv=/alumbrado | op=doPost | comp=perseo-core | msg=incoming event: {"noticeId":"085d9600-2203-11ec-b210-2558567bbc3f","noticeTS":1633015696224,"id":"CAM1-EA-03","type":"VehiclesCounter","isPattern":false,"subservice":"/alumbrado","service":"alcobendas","TimeInstant__type":"Text","TimeInstant":"2021-09-30T15:23:47.501787Z","TimeInstant__ts":1633015427501,"TimeInstant__day":30,"TimeInstant__month":9,"TimeInstant__year":2021,"TimeInstant__hour":15,"TimeInstant__minute":23,"TimeInstant__second":47,"TimeInstant__millisecond":501,"TimeInstant__dayUTC":30,"TimeInstant__monthUTC":9,"TimeInstant__yearUTC":2021,"TimeInstant__hourUTC":15,"TimeInstant__minuteUTC":23,"TimeInstant__secondUTC":47,"TimeInstant__millisecondUTC":501,"addressCountry__type":"Text","addressCountry":"ES","addressLocality__type":"TextUnrestricted","addressLocality":"Magaluf","averageDailyBicycleSpeed__type":"Text","averageDailyBicycleSpeed":100,"averageDailyCarSpeed__type":"Text","averageDailyCarSpeed":100,"averageDailyLorrySpeed__type":"Text","averageDailyLorrySpeed":100,"averageDailyMotorbikeSpeed__type":"Text","averageDailyMotorbikeSpeed":100,"averageDailyVehiclesSpeedAscending__type":"Number","averageDailyVehiclesSpeedAscending":83.988,"averageDailyVehiclesSpeedDescending__type":"Number","averageDailyVehiclesSpeedDescending":67.968,"averageHourlyBicycleSpeed__type":"Text","averageHourlyBicycleSpeed":100,"averageHourlyCarSpeed__type":"Text","averageHourlyCarSpeed":100,"averageHourlyHeadwayTimeAscending__type":"Number","averageHourlyHeadwayTimeAscending":0.2,"averageHourlyHeadwayTimeDescending__type":"Number","averageHourlyHeadwayTimeDescending":0.2,"averageHourlyHeadwayTimeTotal__type":"Number","averageHourlyHeadwayTimeTotal":81,"averageHourlyLorrySpeed__type":"Text","averageHourlyLorrySpeed":100,"averageHourlyMotorbikeSpeed__type":"Text","averageHourlyMotorbikeSpeed":100,"averageHourlyVehiclesSpeedAscending__type":"Number","averageHourlyVehiclesSpeedAscending":87.984,"averageHourlyVehiclesSpeedDescending__type":"Number","averageHourlyVehiclesSpeedDescending":73.98,"averageHourlyVehiclesSpeedTotal__type":"Number","averageHourlyVehiclesSpeedTotal":81,"averageVehiclesSpeedTotal__type":"Number","averageVehiclesSpeedTotal":75.996,"calculatedBicycleNumber__type":"Number","calculatedBicycleNumber":0,"calculatedBicycleNumberAscending__type":"Number","calculatedBicycleNumberAscending":0,"calculatedBicycleNumberDescending__type":"Number","calculatedBicycleNumberDescending":0,"calculatedCarNumber__type":"Number","calculatedCarNumber":15.4,"calculatedCarNumberAscending__type":"Number","calculatedCarNumberAscending":8.8,"calculatedCarNumberDescending__type":"Number","calculatedCarNumberDescending":6.6,"calculatedLorryNumber__type":"Number","calculatedLorryNumber":0,"calculatedLorryNumberAscending__type":"Number","calculatedLorryNumberAscending":0,"calculatedLorryNumberDescending__type":"Number","calculatedLorryNumberDescending":0,"calculatedMotorbikeNumber__type":"Number","calculatedMotorbikeNumber":0,"calculatedMotorbikeNumberAscending__type":"Number","calculatedMotorbikeNumberAscending":0,"calculatedMotorbikeNumberDescending__type":"Number","calculatedMotorbikeNumberDescending":0,"calculatedVehiclesNumber__type":"Number","calculatedVehiclesNumber":15.4,"carNumberAscending__type":"Number","carNumberAscending":8,"carNumberDescending__type":"Number","carNumberDescending":6,"dailyBicycleNumber__type":"Text","dailyBicycleNumber":44,"dailyBicycleNumberAscending__type":"Number","dailyBicycleNumberAscending":100,"dailyBicycleNumberDescending__type":"Number","dailyBicycleNumberDescending":312,"dailyBicycleNumberPercentage__type":"Number","dailyBicycleNumberPercentage":3.279,"dailyBicycleNumberTotal__type":"Number","dailyBicycleNumberTotal":412,"dailyCarNumber__type":"Text","dailyCarNumber":44,"dailyCarNumberAscending__type":"Number","dailyCarNumberAscending":5196,"dailyCarNumberDescending__type":"Number","dailyCarNumberDescending":5274,"dailyCarNumberPercentage__type":"Number","dailyCarNumberPercentage":83.272,"dailyCarNumberTotal__type":"Number","dailyCarNumberTotal":10467,"dailyHeadwayTime__type":"Text","dailyHeadwayTime":0.8,"dailyHeadwayTimeAscending__type":"Number","dailyHeadwayTimeAscending":0.6,"dailyHeadwayTimeDescending__type":"Number","dailyHeadwayTimeDescending":0.5,"dailyHeadwayTimeTotal__type":"Number","dailyHeadwayTimeTotal":0.2,"dailyLorryNumber__type":"Text","dailyLorryNumber":44,"dailyLorryNumberAscending__type":"Number","dailyLorryNumberAscending":230,"dailyLorryNumberDescending__type":"Number","dailyLorryNumberDescending":422,"dailyLorryNumberPercentage__type":"Number","dailyLorryNumberPercentage":5.189,"dailyLorryNumberTotal__type":"Number","dailyLorryNumberTotal":652,"dailyMotorbikeNumber__type":"Text","dailyMotorbikeNumber":44,"dailyMotorbikeNumberAscending__type":"Number","dailyMotorbikeNumberAscending":502,"dailyMotorbikeNumberDescending__type":"Number","dailyMotorbikeNumberDescending":538,"dailyMotorbikeNumberPercentage__type":"Number","dailyMotorbikeNumberPercentage":8.276,"dailyMotorbikeNumberTotal__type":"Number","dailyMotorbikeNumberTotal":1040,"dailyVehiclesNumberAscending__type":"Number","dailyVehiclesNumberAscending":6028,"dailyVehiclesNumberDescending__type":"Number","dailyVehiclesNumberDescending":6544,"dailyVehiclesNumberTotal__type":"Number","dailyVehiclesNumberTotal":12569,"dateCalculatedVehicleNumber__type":"DateTime","dateCalculatedVehicleNumber":"2021-09-30T14:10:08.771Z","dateCalculatedVehicleNumber__ts":1633011008771,"dateCalculatedVehicleNumber__day":30,"dateCalculatedVehicleNumber__month":9,"dateCalculatedVehicleNumber__year":2021,"dateCalculatedVehicleNumber__hour":14,"dateCalculatedVehicleNumber__minute":10,"dateCalculatedVehicleNumber__second":8,"dateCalculatedVehicleNumber__millisecond":771,"dateCalculatedVehicleNumber__dayUTC":30,"dateCalculatedVehicleNumber__monthUTC":9,"dateCalculatedVehicleNumber__yearUTC":2021,"dateCalculatedVehicleNumber__hourUTC":14,"dateCalculatedVehicleNumber__minuteUTC":10,"dateCalculatedVehicleNumber__secondUTC":8,"dateCalculatedVehicleNumber__millisecondUTC":771,"dateCalculatedVehiclesNumber__type":"DateTime","dateCalculatedVehiclesNumber":"2021-09-30T15:27:34.870Z","dateCalculatedVehiclesNumber__ts":1633015654870,"dateCalculatedVehiclesNumber__day":30,"dateCalculatedVehiclesNumber__month":9,"dateCalculatedVehiclesNumber__year":2021,"dateCalculatedVehiclesNumber__hour":15,"dateCalculatedVehiclesNumber__minute":27,"dateCalculatedVehiclesNumber__second":34,"dateCalculatedVehiclesNumber__millisecond":870,"dateCalculatedVehiclesNumber__dayUTC":30,"dateCalculatedVehiclesNumber__monthUTC":9,"dateCalculatedVehiclesNumber__yearUTC":2021,"dateCalculatedVehiclesNumber__hourUTC":15,"dateCalculatedVehiclesNumber__minuteUTC":27,"dateCalculatedVehiclesNumber__secondUTC":34,"dateCalculatedVehiclesNumber__millisecondUTC":870,"description__type":"TextUnrestricted","description":"EA","hourlyHeadwayTime__type":"Text","hourlyHeadwayTime":0.8,"isday__type":"Text","isday":"null","isnight__type":"Text","isnight":"null","location__type":"geo:json","location":"2.517069,39.521311","location__lat":2.517069,"location__lon":39.521311,"location__x":557954.0703117244,"location__y":278225.12813063635,"maxDailyBicycleSpeed__type":"Text","maxDailyBicycleSpeed":100,"maxDailyBicycleSpeed__lat":2.517069,"maxDailyBicycleSpeed__lon":39.521311,"maxDailyBicycleSpeed__x":557954.0703117244,"maxDailyBicycleSpeed__y":278225.12813063635,"maxDailyCarSpeed__type":"Text","maxDailyCarSpeed":100,"maxDailyCarSpeed__lat":2.517069,"maxDailyCarSpeed__lon":39.521311,"maxDailyCarSpeed__x":557954.0703117244,"maxDailyCarSpeed__y":278225.12813063635,"maxDailyLorrySpeed__type":"Text","maxDailyLorrySpeed":100,"maxDailyLorrySpeed__lat":2.517069,"maxDailyLorrySpeed__lon":39.521311,"maxDailyLorrySpeed__x":557954.0703117244,"maxDailyLorrySpeed__y":278225.12813063635,"maxDailyMotorbikeSpeed__type":"Text","maxDailyMotorbikeSpeed":100,"maxDailyMotorbikeSpeed__lat":2.517069,"maxDailyMotorbikeSpeed__lon":39.521311,"maxDailyMotorbikeSpeed__x":557954.0703117244,"maxDailyMotorbikeSpeed__y":278225.12813063635,"maxDailyVehiclesSpeedAscending__type":"Number","maxDailyVehiclesSpeedAscending":129.996,"maxDailyVehiclesSpeedAscending__lat":2.517069,"maxDailyVehiclesSpeedAscending__lon":39.521311,"maxDailyVehiclesSpeedAscending__x":557954.0703117244,"maxDailyVehiclesSpeedAscending__y":278225.12813063635,"maxDailyVehiclesSpeedDescending__type":"Number","maxDailyVehiclesSpeedDescending":128.988,"maxDailyVehiclesSpeedDescending__lat":2.517069,"maxDailyVehiclesSpeedDescending__lon":39.521311,"maxDailyVehiclesSpeedDescending__x":557954.0703117244,"maxDailyVehiclesSpeedDescending__y":278225.12813063635,"maxDailyVehiclesSpeedTotal__type":"Number","maxDailyVehiclesSpeedTotal":129.996,"maxDailyVehiclesSpeedTotal__lat":2.517069,"maxDailyVehiclesSpeedTotal__lon":39.521311,"maxDailyVehiclesSpeedTotal__x":557954.0703117244,"maxDailyVehiclesSpeedTotal__y":278225.12813063635,"maxHourlyBicycleSpeed__type":"Text","maxHourlyBicycleSpeed":100,"maxHourlyBicycleSpeed__lat":2.517069,"maxHourlyBicycleSpeed__lon":39.521311,"maxHourlyBicycleSpeed__x":557954.0703117244,"maxHourlyBicycleSpeed__y":278225.12813063635,"maxHourlyCarSpeed__type":"Text","maxHourlyCarSpeed":100,"maxHourlyCarSpeed__lat":2.517069,"maxHourlyCarSpeed__lon":39.521311,"maxHourlyCarSpeed__x":557954.0703117244,"maxHourlyCarSpeed__y":278225.12813063635,"maxHourlyLorrySpeed__type":"Text","maxHourlyLorrySpeed":100,"maxHourlyLorrySpeed__lat":2.517069,"maxHourlyLorrySpeed__lon":39.521311,"maxHourlyLorrySpeed__x":557954.0703117244,"maxHourlyLorrySpeed__y":278225.12813063635,"maxHourlyMotorbikeSpeed__type":"Text","maxHourlyMotorbikeSpeed":100,"maxHourlyMotorbikeSpeed__lat":2.517069,"maxHourlyMotorbikeSpeed__lon":39.521311,"maxHourlyMotorbikeSpeed__x":557954.0703117244,"maxHourlyMotorbikeSpeed__y":278225.12813063635,"maxHourlyVehiclesSpeedAscending__type":"Number","maxHourlyVehiclesSpeedAscending":123.984,"maxHourlyVehiclesSpeedAscending__lat":2.517069,"maxHourlyVehiclesSpeedAscending__lon":39.521311,"maxHourlyVehiclesSpeedAscending__x":557954.0703117244,"maxHourlyVehiclesSpeedAscending__y":278225.12813063635,"maxHourlyVehiclesSpeedDescending__type":"Number","maxHourlyVehiclesSpeedDescending":118.98,"maxHourlyVehiclesSpeedDescending__lat":2.517069,"maxHourlyVehiclesSpeedDescending__lon":39.521311,"maxHourlyVehiclesSpeedDescending__x":557954.0703117244,"maxHourlyVehiclesSpeedDescending__y":278225.12813063635,"maxHourlyVehiclesSpeedTotal__type":"Number","maxHourlyVehiclesSpeedTotal":123.984,"maxHourlyVehiclesSpeedTotal__lat":2.517069,"maxHourlyVehiclesSpeedTotal__lon":39.521311,"maxHourlyVehiclesSpeedTotal__x":557954.0703117244,"maxHourlyVehiclesSpeedTotal__y":278225.12813063635,"monthlyBicycleNumber__type":"Text","monthlyBicycleNumber":560,"monthlyBicycleNumber__lat":2.517069,"monthlyBicycleNumber__lon":39.521311,"monthlyBicycleNumber__x":557954.0703117244,"monthlyBicycleNumber__y":278225.12813063635,"monthlyCarNumber__type":"Text","monthlyCarNumber":560,"monthlyCarNumber__lat":2.517069,"monthlyCarNumber__lon":39.521311,"monthlyCarNumber__x":557954.0703117244,"monthlyCarNumber__y":278225.12813063635,"monthlyLorryNumber__type":"Text","monthlyLorryNumber":560,"monthlyLorryNumber__lat":2.517069,"monthlyLorryNumber__lon":39.521311,"monthlyLorryNumber__x":557954.0703117244,"monthlyLorryNumber__y":278225.12813063635,"monthlyMotorbikeNumber__type":"Text","monthlyMotorbikeNumber":560,"monthlyMotorbikeNumber__lat":2.517069,"monthlyMotorbikeNumber__lon":39.521311,"monthlyMotorbikeNumber__x":557954.0703117244,"monthlyMotorbikeNumber__y":278225.12813063635,"ocaso__type":"Text","ocaso":1633101337000,"ocaso__lat":2.517069,"ocaso__lon":39.521311,"ocaso__x":557954.0703117244,"ocaso__y":278225.12813063635,"orto__type":"Text","orto":1633057803000,"orto__lat":2.517069,"orto__lon":39.521311,"orto__x":557954.0703117244,"orto__y":278225.12813063635,"postalCode__type":"Number","postalCode":7181,"postalCode__lat":2.517069,"postalCode__lon":39.521311,"postalCode__x":557954.0703117244,"postalCode__y":278225.12813063635,"ratioDay__type":"Number","ratioDay":0.05,"ratioDay__lat":2.517069,"ratioDay__lon":39.521311,"ratioDay__x":557954.0703117244,"ratioDay__y":278225.12813063635,"ratioNigth__type":"Number","ratioNigth":0.2,"ratioNigth__lat":2.517069,"ratioNigth__lon":39.521311,"ratioNigth__x":557954.0703117244,"ratioNigth__y":278225.12813063635,"ratioTwiglight__type":"Number","ratioTwiglight":0.1,"ratioTwiglight__lat":2.517069,"ratioTwiglight__lon":39.521311,"ratioTwiglight__x":557954.0703117244,"ratioTwiglight__y":278225.12813063635,"roadPointID__type":"Text","roadPointID":"Spain-RoadPoint-EA-03-14-A","roadPointID__lat":2.517069,"roadPointID__lon":39.521311,"roadPointID__x":557954.0703117244,"roadPointID__y":278225.12813063635,"sourceOriginEventID__type":"Text","sourceOriginEventID":21,"sourceOriginEventID__lat":2.517069,"sourceOriginEventID__lon":39.521311,"sourceOriginEventID__x":557954.0703117244,"sourceOriginEventID__y":278225.12813063635,"sourceOriginator__type":"Text","sourceOriginator":"PlasticConsellMallorca1","sourceOriginator__lat":2.517069,"sourceOriginator__lon":39.521311,"sourceOriginator__x":557954.0703117244,"sourceOriginator__y":278225.12813063635,"streetAddress__type":"TextUnrestricted","streetAddress":"Ma-1. salida 14 dirección Magaluf, El Toro","streetAddress__lat":2.517069,"streetAddress__lon":39.521311,"streetAddress__x":557954.0703117244,"streetAddress__y":278225.12813063635,"streetNumber__type":"Number","streetNumber":14,"streetNumber__lat":2.517069,"streetNumber__lon":39.521311,"streetNumber__x":557954.0703117244,"streetNumber__y":278225.12813063635,"weeklyBicycleNumber__type":"Text","weeklyBicycleNumber":560,"weeklyBicycleNumber__lat":2.517069,"weeklyBicycleNumber__lon":39.521311,"weeklyBicycleNumber__x":557954.0703117244,"weeklyBicycleNumber__y":278225.12813063635,"weeklyCarNumber__type":"Text","weeklyCarNumber":560,"weeklyCarNumber__lat":2.517069,"weeklyCarNumber__lon":39.521311,"weeklyCarNumber__x":557954.0703117244,"weeklyCarNumber__y":278225.12813063635,"weeklyLorryNumber__type":"Text","weeklyLorryNumber":560,"weeklyLorryNumber__lat":2.517069,"weeklyLorryNumber__lon":39.521311,"weeklyLorryNumber__x":557954.0703117244,"weeklyLorryNumber__y":278225.12813063635,"weeklyMotorbikeNumber__type":"Text","weeklyMotorbikeNumber":560,"weeklyMotorbikeNumber__lat":2.517069,"weeklyMotorbikeNumber__lon":39.521311,"weeklyMotorbikeNumber__x":557954.0703117244,"weeklyMotorbikeNumber__y":278225.12813063635,"stripped":{"id":"CAM1-EA-03","type":"VehiclesCounter","TimeInstant":{"type":"Text","value":"2021-09-30T15:23:47.501787Z","metadata":{}},"addressCountry":{"type":"Text","value":"ES","metadata":{}},"addressLocality":{"type":"TextUnrestricted","value":"Magaluf","metadata":{}},"averageDailyBicycleSpeed":{"type":"Text","value":100,"metadata":{}},"averageDailyCarSpeed":{"type":"Text","value":100,"metadata":{}},"averageDailyLorrySpeed":{"type":"Text","value":100,"metadata":{}},"averageDailyMotorbikeSpeed":{"type":"Text","value":100,"metadata":{}},"averageDailyVehiclesSpeedAscending":{"type":"Number","value":83.988,"metadata":{}},"averageDailyVehiclesSpeedDescending":{"type":"Number","value":67.968,"metadata":{}},"averageHourlyBicycleSpeed":{"type":"Text","value":100,"metadata":{}},"averageHourlyCarSpeed":{"type":"Text","value":100,"metadata":{}},"averageHourlyHeadwayTimeAscending":{"type":"Number","value":0.2,"metadata":{}},"averageHourlyHeadwayTimeDescending":{"type":"Number","value":0.2,"metadata":{}},"averageHourlyHeadwayTimeTotal":{"type":"Number","value":81,"metadata":{}},"averageHourlyLorrySpeed":{"type":"Text","value":100,"metadata":{}},"averageHourlyMotorbikeSpeed":{"type":"Text","value":100,"metadata":{}},"averageHourlyVehiclesSpeedAscending":{"type":"Number","value":87.984,"metadata":{}},"averageHourlyVehiclesSpeedDescending":{"type":"Number","value":73.98,"metadata":{}},"averageHourlyVehiclesSpeedTotal":{"type":"Number","value":81,"metadata":{}},"averageVehiclesSpeedTotal":{"type":"Number","value":75.996,"metadata":{}},"calculatedBicycleNumber":{"type":"Number","value":0,"metadata":{}},"calculatedBicycleNumberAscending":{"type":"Number","value":0,"metadata":{}},"calculatedBicycleNumberDescending":{"type":"Number","value":0,"metadata":{}},"calculatedCarNumber":{"type":"Number","value":15.4,"metadata":{}},"calculatedCarNumberAscending":{"type":"Number","value":8.8,"metadata":{}},"calculatedCarNumberDescending":{"type":"Number","value":6.6,"metadata":{}},"calculatedLorryNumber":{"type":"Number","value":0,"metadata":{}},"calculatedLorryNumberAscending":{"type":"Number","value":0,"metadata":{}},"calculatedLorryNumberDescending":{"type":"Number","value":0,"metadata":{}},"calculatedMotorbikeNumber":{"type":"Number","value":0,"metadata":{}},"calculatedMotorbikeNumberAscending":{"type":"Number","value":0,"metadata":{}},"calculatedMotorbikeNumberDescending":{"type":"Number","value":0,"metadata":{}},"calculatedVehiclesNumber":{"type":"Number","value":15.4,"metadata":{}},"carNumberAscending":{"type":"Number","value":8,"metadata":{}},"carNumberDescending":{"type":"Number","value":6,"metadata":{}},"dailyBicycleNumber":{"type":"Text","value":44,"metadata":{}},"dailyBicycleNumberAscending":{"type":"Number","value":100,"metadata":{}},"dailyBicycleNumberDescending":{"type":"Number","value":312,"metadata":{}},"dailyBicycleNumberPercentage":{"type":"Number","value":3.279,"metadata":{}},"dailyBicycleNumberTotal":{"type":"Number","value":412,"metadata":{}},"dailyCarNumber":{"type":"Text","value":44,"metadata":{}},"dailyCarNumberAscending":{"type":"Number","value":5196,"metadata":{}},"dailyCarNumberDescending":{"type":"Number","value":5274,"metadata":{}},"dailyCarNumberPercentage":{"type":"Number","value":83.272,"metadata":{}},"dailyCarNumberTotal":{"type":"Number","value":10467,"metadata":{}},"dailyHeadwayTime":{"type":"Text","value":0.8,"metadata":{}},"dailyHeadwayTimeAscending":{"type":"Number","value":0.6,"metadata":{}},"dailyHeadwayTimeDescending":{"type":"Number","value":0.5,"metadata":{}},"dailyHeadwayTimeTotal":{"type":"Number","value":0.2,"metadata":{}},"dailyLorryNumber":{"type":"Text","value":44,"metadata":{}},"dailyLorryNumberAscending":{"type":"Number","value":230,"metadata":{}},"dailyLorryNumberDescending":{"type":"Number","value":422,"metadata":{}},"dailyLorryNumberPercentage":{"type":"Number","value":5.189,"metadata":{}},"dailyLorryNumberTotal":{"type":"Number","value":652,"metadata":{}},"dailyMotorbikeNumber":{"type":"Text","value":44,"metadata":{}},"dailyMotorbikeNumberAscending":{"type":"Number","value":502,"metadata":{}},"dailyMotorbikeNumberDescending":{"type":"Number","value":538,"metadata":{}},"dailyMotorbikeNumberPercentage":{"type":"Number","value":8.276,"metadata":{}},"dailyMotorbikeNumberTotal":{"type":"Number","value":1040,"metadata":{}},"dailyVehiclesNumberAscending":{"type":"Number","value":6028,"metadata":{}},"dailyVehiclesNumberDescending":{"type":"Number","value":6544,"metadata":{}},"dailyVehiclesNumberTotal":{"type":"Number","value":12569,"metadata":{}},"dateCalculatedVehicleNumber":{"type":"DateTime","value":"2021-09-30T14:10:08.771Z","metadata":{}},"dateCalculatedVehiclesNumber":{"type":"DateTime","value":"2021-09-30T15:27:34.870Z","metadata":{}},"description":{"type":"TextUnrestricted","value":"EA","metadata":{}},"hourlyHeadwayTime":{"type":"Text","value":0.8,"metadata":{}},"isday":{"type":"Text","value":"null","metadata":{}},"isnight":{"type":"Text","value":"null","metadata":{}},"location":{"type":"geo:json","value":{"type":"Point","coordinates":[2.517069,39.521311]},"metadata":{}},"maxDailyBicycleSpeed":{"type":"Text","value":100,"metadata":{}},"maxDailyCarSpeed":{"type":"Text","value":100,"metadata":{}},"maxDailyLorrySpeed":{"type":"Text","value":100,"metadata":{}},"maxDailyMotorbikeSpeed":{"type":"Text","value":100,"metadata":{}},"maxDailyVehiclesSpeedAscending":{"type":"Number","value":129.996,"metadata":{}},"maxDailyVehiclesSpeedDescending":{"type":"Number","value":128.988,"metadata":{}},"maxDailyVehiclesSpeedTotal":{"type":"Number","value":129.996,"metadata":{}},"maxHourlyBicycleSpeed":{"type":"Text","value":100,"metadata":{}},"maxHourlyCarSpeed":{"type":"Text","value":100,"metadata":{}},"maxHourlyLorrySpeed":{"type":"Text","value":100,"metadata":{}},"maxHourlyMotorbikeSpeed":{"type":"Text","value":100,"metadata":{}},"maxHourlyVehiclesSpeedAscending":{"type":"Number","value":123.984,"metadata":{}},"maxHourlyVehiclesSpeedDescending":{"type":"Number","value":118.98,"metadata":{}},"maxHourlyVehiclesSpeedTotal":{"type":"Number","value":123.984,"metadata":{}},"monthlyBicycleNumber":{"type":"Text","value":560,"metadata":{}},"monthlyCarNumber":{"type":"Text","value":560,"metadata":{}},"monthlyLorryNumber":{"type":"Text","value":560,"metadata":{}},"monthlyMotorbikeNumber":{"type":"Text","value":560,"metadata":{}},"ocaso":{"type":"Text","value":1633101337000,"metadata":{}},"orto":{"type":"Text","value":1633057803000,"metadata":{}},"postalCode":{"type":"Number","value":7181,"metadata":{}},"ratioDay":{"type":"Number","value":0.05,"metadata":{}},"ratioNigth":{"type":"Number","value":0.2,"metadata":{}},"ratioTwiglight":{"type":"Number","value":0.1,"metadata":{}},"roadPointID":{"type":"Text","value":"Spain-RoadPoint-EA-03-14-A","metadata":{}},"sourceOriginEventID":{"type":"Text","value":21,"metadata":{}},"sourceOriginator":{"type":"Text","value":"PlasticConsellMallorca1","metadata":{}},"streetAddress":{"type":"TextUnrestricted","value":"Ma-1. salida 14 dirección Magaluf, El Toro","metadata":{}},"streetNumber":{"type":"Number","value":14,"metadata":{}},"weeklyBicycleNumber":{"type":"Text","value":560,"metadata":{}},"weeklyCarNumber":{"type":"Text","value":560,"metadata":{}},"weeklyLorryNumber":{"type":"Text","value":560,"metadata":{}},"weeklyMotorbikeNumber":{"type":"Text","value":560,"metadata":{}}}}

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/559
