### ISSUE TITLE
Object values should be delivered to perseo-core

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#576]
Perseo-fe is dealing with object values in order to ease the acces to its keys, but it doesn't deliver the object value itself. The original value should also be delivered to perseo-core

moreover, parse geo:json also as usual JSON not in a special way (maybe we should keep both for BW compatibility). So:

```
{
"loc": {
"type": "Point",
"coordinates": [
53.0859375,
53.12040528310657
]
}
}
```

will be expanded as:

loc__coordinates__0 : 53.0859375
loc__coordinates__1 : 53.12040528310657
loc__lat: 53.0859375
loc__long: 53.12040528310657
loc:__type: "Point"

**Comment by AlvaroVega** [comment]
i.e. you can use:
```
select *,"miregla" as ruleName, cast(stripped?, java.util.Map).get("id") as myId from pattern [every ev=iotEvent((cast(`id`?, String) regexp "test"))] 
```

`
cast(stripped?, java.util.Map).get("id")
`
