### ISSUE TITLE
Starting perseo-fe result in `AuthenticationError`

### ISSUE THREAD

**Issue by devrnt** [telefonicaid/perseo-fe#607]
Starting `perseo-fe` result in `AuthenticationError`, see logs down below. 

* Mongodb version is `v3.6.23`
* Perseo-fe image version: `1.19.0`

This is caused by the following line https://github.com/telefonicaid/perseo-fe/blob/master/bin/perseo#L154 since it's interpreted as `defaultauthdb` in mongodb. This issue seems only applicable if the mongodb has auth enabled. 

This issue can be fixed by supplying an `authSource` to the mongo connection string. See mongo db connection string components: https://docs.mongodb.com/manual/reference/connection-string/#components. I quote `/defaultauthdb`:
> Optional. The authentication database to use if the connection string includes username:password@ authentication credentials but the authSource option is unspecified.
> If both authSource and defaultauthdb are unspecified, the client will attempt to authenticate the specified user to the admin database.

At the moment it is unable to append anything after the mongodb string (except for the mongo `replicatset`). 

Example: currently this is the mongo db connection string (inside the perseo component): `mongodb://[user]:[password]@[host]/cep`, this doesn't work. However when `authSource` is appended it works: `mongodb://[user]:[password]@[host]/cep?authSource=[authSource]`. 

**Suggestions**
Either give the possibility to supply a full mongo db connection string (and parse it afterwards to extract the individual fields) or add some mongodb "component mappings", like you did for `PERSEO_MONGO_REPLICASET`

**perseo-fe logs**
```
 time=2021-11-23T15:18:37.103Z | lvl=ERROR | corr=n/a | trans=n/a | op=checkDB | comp=perseo-fe | msg=connect failed to connect to server [host:port] on first connect [MongoError: Authentication failed │
│     at Connection.messageHandler (/opt/perseo-fe/node_modules/mongodb/lib/core/connection/connection.js:359:19)                                                                                              │
│     at Connection.emit (events.js:314:20)                                                                                                                                                                    │
│     at Connection.EventEmitter.emit (domain.js:506:15)                                                                                                                                                       │
│     at processMessage (/opt/perseo-fe/node_modules/mongodb/lib/core/connection/connection.js:451:10)                                                                                                         │
│     at Socket.<anonymous> (/opt/perseo-fe/node_modules/mongodb/lib/core/connection/connection.js:620:15)                                                                                                     │
│     at Socket.emit (events.js:314:20)                                                                                                                                                                        │
│     at Socket.EventEmitter.emit (domain.js:506:15)                                                                                                                                                           │
│     at addChunk (_stream_readable.js:297:12)                                                                                                                                                                 │
│     at readableAddChunk (_stream_readable.js:272:9)                                                                                                                                                          │
│     at Socket.Readable.push (_stream_readable.js:213:10) {                                                                                                                                                   │
│   ok: 0,                                                                                                                                                                                                     │
│   code: 18,                                                                                                                                                                                                  │
│   codeName: 'AuthenticationFailed'                                                                                                                                                                           │
│ }]     
```

**Mongo db logs**
```
SCRAM-SHA-1 authentication failed for root on cep from client [host]:[port] ; UserNotFound: Could not find user root@cep
```

**Comment by fgalan** [comment]
Thank you very much for so detailed report!

I think the best solution would be the alternative

> add some mongodb "component mappings", like you did for `PERSEO_MONGO_REPLICASET`

Maybe you could propose a fix based in that idea in a pull request so we can have a look and eventually merge, please?

Thanks!
