### ISSUE TITLE
BUG Strange meaning of perseo-fe variable that can lead to mistakes

### ISSUE THREAD

**Issue by cesarjorgemartinez** [telefonicaid/perseo-fe#619]
Hi,

I am involved in finding a strange problem with cep rule triggers when trying to perform an action on another subservice than the one that CEP rule belongs to.

Then I find this link: https://github.com/telefonicaid/perseo-fe/blob/master/docs/admin/configuration.md

```
PERSEO_ORION_URL | Full URL of the Orion Context Broker (e.g: http://64.124.28.15:1026).
PERSEO_PEP_URL | Full URL of the Pep (Context Broker) (e.g: http://64.124.28.15:10026).  This URL will be used instead of PERSEO_ORION_URL when updateAction  rule has set a non empty value for service and subservice.
```

Then I need to change these vars to resume my analysis:
PERSEO_ORION_URL -> OK
PERSEO_PEP_URL -> PERSEO_PEP_ORION_URL

And generate a new version of perseo-fe (1.21.0)

Regards,
Cesar Jorge

**Comment by mrutid** [comment]
This not a bug.

**Comment by cesarjorgemartinez** [comment]
This problem continues to exist. It is a problem of meaning that leads to error in the following terms:
If someone read PERSEO_PEP_URL quickly, then interprets the value as (this has already happen):

```
PERSEO_PEP_URL=http://pro-core-smc-pep-perseo-fe:9090
```

**Comment by fgalan** [comment]
Nobody should read documentation "quickly", but "carefully" ;) And if you read carefully the PERSEO_PEP_URL documentation at https://github.com/telefonicaid/perseo-fe/blob/master/docs/admin/configuration.md you would see:

> Full URL of the Pep (Context Broker) 

which clearly specifies that it refers to the PEP of CB  (ant not to the PEP of CEP)

I agrees that the name for the env var is not the perfect one, but the backward compatibility issues that changing the name would bring are very much worse, from my point of view.

**Comment by cesarjorgemartinez** [comment]
but you are going to change it even if it is not considered a bug, what version will it be in?

**Comment by fgalan** [comment]
> but you are going to change it even if it is not considered a bug, what version will it be in?

No, we are not going to change. Doing so will bring backward compatibility problems in existing deployment bigger than the advantages of changing the env var name.

**Comment by cesarjorgemartinez** [comment]
What are those non-compatibility problems? I solve it for you
