### ISSUE TITLE
bad src/subservice in warn logs about checkNonSignal

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#624]
pro-core-smc-perseo-fe-5f589f6bcc-t54lt smc-perseo-fe-container time=2022-02-03T09:44:15.227Z | lvl=WARN | corr=n/a | trans=n/a | op=checkNonSignal | comp=perseo-fe | srv=ZZZZZ | subsrv=/ | msg=Check interval 50000 too big for rule (XXXXi, /YYY, alarma_nosignal_noiselevel)

where XXXXX should be equal to ZZZZZ

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/626
