### ISSUE TITLE
External CB URL in Update Action

### ISSUE THREAD

**Issue by manucarrace** [telefonicaid/perseo-fe#625]
Current implementation of perseo allows to execute an entity update on a different service and subservice from the current event (or the service/subservice rule if no event is sent). 

When the service used by update action is different from current event service, Orion PEP URL is used instead of Orion URL. This PEP URL is setted in configuration time.

It is proposed to have the possibility to set the PEP URL in the action, so you can update entities from an external CB, being the defaul value the internal PEP URL.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/629
