### ISSUE TITLE
411 error ContentLengthRequired happens when sending request to orion from perseo

### ISSUE THREAD

**Issue by Yufei-Yufei** [telefonicaid/perseo-fe#636]
Hi, team. I am trying to PATCH entities of orion from perseo using its rules but always get 411 error "ContentLengthRequired". Postman and curl both work fine with sending HTTP requests to orion because these two tools automatically generate Content-Length header, but perseo does not. Is there a way to send HTTP request to orion from perseo with its rules?

Additionally, I also tried to add Content-Length header to my perseo rule but don't know what value I should put there. And whatever value I define for Content-Length, orion returns 411 error. 

Could anyone please help me out...

**Comment by AlvaroVega** [comment]
Comes from https://github.com/telefonicaid/perseo-fe/issues/633

**Comment by fgalan** [comment]
> Not sure if we allow POST with a non json-body

The only operation allowed in NGSIv2 API with a non json-body is `PUT /v2/entities/{entityId}/attrs/{attrName}/value` which used PUT verb, not POST.

**Comment by AlvaroVega** [comment]
But the meaning of postAction is allow make an http request to an endpoint which would not be ngsi. 

Moreover when action has a template then perseo-fe do a post with a non json body
https://github.com/telefonicaid/perseo-fe/blob/master/docs/API/plain_rules.md#http-request-action

json: optional, an object that will be sent as JSON. String substitution will be performed in the keys and values of the object's fields. If present, it overrides template from action

https://github.com/telefonicaid/perseo-fe/blob/60e77288587d0c150c2de005f3ddd480e20893da/lib/models/postAction.js#L39-L40

**Comment by fgalan** [comment]
> But the meaning of postAction is allow make an http request to an endpoint which would not be ngsi.
> 
> Moreover when action has a template then perseo-fe do a post with a non json body https://github.com/telefonicaid/perseo-fe/blob/master/docs/API/plain_rules.md#http-request-action
> 
> json: optional, an object that will be sent as JSON. String substitution will be performed in the keys and values of the object's fields. If present, it overrides template from action
> 
> https://github.com/telefonicaid/perseo-fe/blob/60e77288587d0c150c2de005f3ddd480e20893da/lib/models/postAction.js#L39-L40

Thus is seems we should allow both JSON and plain text in requests actions, as we could have endpoint on both classes. Is my understanding correct?
