### ISSUE TITLE
TypeError in cbDoReqUpdAxn

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#659]
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'code' of null
    at cbDoReqUpdAxn (/opt/perseo-fe/lib/models/updateAction.js:610:27)
    at /opt/perseo-fe/lib/models/updateAction.js:554:13

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/660
