### ISSUE TITLE
Include full json in event to perseo-core (array value)

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#662]
maybe related: https://github.com/telefonicaid/perseo-fe/pull/582 but in a non string form

and related with https://github.com/telefonicaid/perseo-fe/issues/377 (stripped just for debugging?)

**Comment by AlvaroVega** [comment]
{"stripped":{"tThresholds":{"metadata":{},"type":"List","value":[5,10,15]},"tStatus":{"metadata":{},"type":"List","value":["cold","warm","hot"]},"temperature":{"metadata":{},"type":"Number","value":12},"id":"prueba_umbrales","temperatureThreshold":{"metadata":{},"type":"Threshold","value":[{"value":5,"status":"cold"},{"value":15,"status":"hot"}]},"type":"prueba"},"type":"prueba","isPattern":false,"subservice":"/pruebas","temperatureThreshold__0__value":5,"temperatureThreshold__1__value":15,"tThresholds__2":15,"tThresholds__1":10,"tThresholds__0":5,"temperatureThreshold__1__status":"hot","tStatus__2":"hot","temperature":12,"temperatureThreshold__type":"Threshold","id":"prueba_umbrales","tThresholds__type":"List","temperatureThreshold__0__status":"cold","tStatus__0":"cold","tStatus__1":"warm","noticeTS":1650448694425,"temperature__type":"Number","noticeId":"65045890-c090-11ec-a1a3-3f1f2a4fc6e3","tStatus__type":"List","temperatureThreshold__0":"{\"value\":5,\"status\":\"cold\"}","service":"alcobendas","temperatureThreshold__1":"{\"value\":15,\"status\":\"hot\"}"}


it seems problem is when object in an array:
temperatureThreshold  [{"value":5,"status":"cold"},{"value":15,"status":"hot"}]

is expanded to 
temperatureThreshold__0":"{\"value\":5,\"status\":\"cold\"}
temperatureThreshold__1":"{\"value\":15,\"status\":\"hot\"}"}

but there is not a temperatureThreshold =  [{"value":5,"status":"cold"},{"value":15,"status":"hot"}]

**Comment by AlvaroVega** [comment]
https://github.com/telefonicaid/perseo-fe/blob/9941262c6fada6b0176bad9b35f75fdebbe801e0/lib/models/notices.js#L120-L219

**Comment by AlvaroVega** [comment]
Perseo core reception:

https://github.com/telefonicaid/perseo-core/blob/51ba8dcf7dc5aa027a074b74942e3c9308f57222/perseo-main/src/main/java/com/telefonica/iot/perseo/EventsServlet.java#L85-L91

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/671
