### ISSUE TITLE
From necessary for SMS action

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/perseo-fe#67]
The outgoing SMS must have a 'from' field

Reported by @mcarracedo

**Comment by fgalan** [comment]
Fixed in https://github.com/telefonicaid/perseo-fe/pull/66.

@mcarracedo please close this issue as soon as you check it has been actually fixed.

**Comment by iariasleon** [comment]
LGTM
```
{"to":["tel:+34123456789"],
 "message":"Element room2 has value <<<300>>> \n -- (SMS rule)",
 "from":"tel:22012;phone-context=+34"
}
```

**Comment by iariasleon** [comment]
I close this issue because @mcarracedo do not have visibility about this github project
