### ISSUE TITLE
unnecessary preprocessing for DateTime and Location

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#706]
There are some unnecessary preprocessing that should be removed.

TimeInstant attributes should remain as ISO-STRING or NULL
Location attributes should remain as GEO:JSON or NULL 

https://github.com/telefonicaid/perseo-fe/blob/e7cf97a3615676341a6f10962597d84c6bc2650e/lib/models/notices.js

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/713
