### ISSUE TITLE
update action with filter in a timed rule is not retrying after first failure

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#708]
With this rule: 
`
    {
      "name": "streetlight_keep_alive_test",
      "description": "KeepAlive periódico contra StreetlightControlCabinet",
      "text": "select *, current_timestamp.format(\"yyyy-MM-dd'T'HH:mm:ss.SSSX\") as currentTS from pattern [every timer:at(*/5, *, *, *, *)]",
      "action": {
        "type": "update",
        "version": 2,
        "parameters": {
          "actionType": "UPDATE",
          "filter": {
            "q": "enableKeepAlive==true",
            "type": "StreetlightControlCabinet"
          },
          "attributes": [
            {
              "name": "setKeepAliveTest",
              "type": "TextUnrestricted",
              "value": "${currentTS}"
            }
          ]
        }
      }
    }
`
If update entitiies fails then action of timed ruled is not retrying as expected

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/707
