### ISSUE TITLE
release.sh. Check there are no staged changes

### ISSUE THREAD

**Issue by crbrox** [telefonicaid/perseo-fe#71]
The release script should check there are no staged changes that can cause errors

**Comment by fgalan** [comment]
It is not a critical change so I'd suggest not implementing this fix yet. Let's wait to define how the "global script" would be (we may even change scripting technology, e.g. from bash to Python) ant take this item as "requiement" for that "global script".

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/issues/103
