### ISSUE TITLE
Error for null DateTimes: We do not need to parse dates - Legacy function -

### ISSUE THREAD

**Issue by mrutid** [telefonicaid/perseo-fe#712]
In general Dates is Perseo EPL are managed from its string representation:

```
EPL-RECIPES
(DATE->STRING): current_timestamp().format(\"yyyy-MM-dd'T'HH:mm:ss.SSSX\")
(STRING->DATE): cast(lastnotif, date, dateformat: 'iso')
```

We don't need to do the extra Date parsing Perseo does, it's not necessary and a waste of memory.

https://github.com/telefonicaid/perseo-fe/blob/e7cf97a3615676341a6f10962597d84c6bc2650e/lib/models/notices.js#L80

We should remove this parsing (and others: like JSON parse), but for backward compatibility maybe it is better to be able to support "invalid Dates" like null, avoiding extra parsing, and marking the parsing as "legacy". 

In my opinion its better to  remove the functionality right now and state the "new" proposed way of working in release notes (its just a matter of adapting rules, not code).

**Comment by fgalan** [comment]
After some discussion, we think it's better not keep backward compatibility in this case. In the case of old rules no longer working after the modifications, it would be pretty easy to fix them.

**Comment by AlvaroVega** [comment]
Remove also `stripped` collection and others prepared fields

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/713
