### ISSUE TITLE
remove support for ngsiv1: notify and actions

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#714]
https://github.com/telefonicaid/perseo-fe/blob/master/docs/API/plain_rules.md#update-attribute-action
version: optional, The NGSI version for the update action. Set this attribute to 2 or "2" if you want to use NGSv2 format. 2 by default.

Should we need be sure none rule in production is using ngsiv1 ?

**Comment by fgalan** [comment]
NGSI versions is related with the notification format but I understand that the rule itself (EPL, etc.) doesn't get impacted by NGSI version (as the "core concepts" used by the rule are the same: entities, atributes, etc.).

However, it would be wise to know how many subscriptions in production are using ngsiv1 format. It should be easy using an ad hoc query to the database.

**Comment by fgalan** [comment]
This issue involves two tasks

- [ ] Remove NGSIv1 support in ingress notifications (this is the one I think is not problematic, see my previous comment)
- [ ] Remove NGSIv1 support in egress update action (this one will require manual change of existing rules)
