### ISSUE TITLE
Support sending XML payloads with PostAction

### ISSUE THREAD

**Issue by rg2011** [telefonicaid/perseo-fe#763]
I'm trying to use the POST Action to send an HTTP Request with an XML payload, but the payload is getting *stringified* before being sent (i.e. it gets enclosed in quotes), so it is not valid XML.

This is my action (obfuscating the URL and actual payload):

```json
 {
            "type": "post",
            "parameters": {
                "url": "https://webhook.site/***OFUSCATED***",
                "method": "POST",
                "headers": {
                    "Content-Type": "application/soap+xml; charset=utf-8"
                }
            },
            "template": "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<soap:Envelope xmlns:soap=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:ser=\"http://ofuscated\">\n    <soap:Header />\n    <soap:Body>\n${payload}</soap:Body>\n</soap:Envelope>"
        }
```

The `${payload}` inside the template is properly replaced, but the webhook receiver gets the whole message encoded within quotes:

![imagen](https://github.com/telefonicaid/perseo-fe/assets/52279456/bd6e9b5f-de68-44fe-a9d0-c253fc18b736)

I believe the problem lies here: https://github.com/telefonicaid/perseo-fe/blob/582b00cb3a14e040163e3771b296710e498ef6fb/lib/models/postAction.js#L61-L64

Calling `JSON.stringify` on a string returns a quouted string, e.g. `JSON.stringify("hello") === '"hello"'`. If `options.text` is already a string, I think it shouldn't be stringified. If the users do want the payload to be quoted, they can use the `json` option, or add the quotes in the template itself.

**Comment by mrutid** [comment]
At (private) beaches-vertical:
  {
                    "type": "post",
                    "template": "<?xml version='1.0' encoding='UTF-8'?><soapenv:Envelope xmlns:soapenv='http://schemas.xmlsoap.org/soap/envelope/' xmlns:xsd='http://www.w3.org/2001/XMLSchema' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'><soapenv:Body><smsTextSubmitReq xmlns='http://www.telefonica.es/MI/InterfazSimplificado/schemas'><Version xmlns=''>1.0</Version><Authorization xmlns=''>XXXXXXXXXXXXXX</Authorization><Sender xmlns=''>XXXXXXXXX</Sender><Recipients xmlns=''><To>${telefono}</To></Recipients><SMSText xmlns=''>XXXXXXXXXXXXX</SMSText><DeliveryReport xmlns=''>All</DeliveryReport></smsTextSubmitReq></soapenv:Body></soapenv:Envelope>",
                    "parameters": {
                        "url": "https://www.mensajerianegocios.movistar.es/XXXXXXXXXXX",
                        "method": "POST",
                        "headers": {
                            "Content-type": "application/soap+xml;charset=UTF-8",
                            "SOAPAction": "smsTextSubmit"
                        }
                    }
                }

we used a similar rule that worked. So it's weird. I Don't see new adds or regresion code, but I agree in the double quoting problem you state.

The code comment seems to address the case of template "string" or Buffer... so why do we need to stringify? is there any chance to get JSON in the template? what happened in that case? (I suppose JSON should be managed as the XML does) except we were using it as a constant in order to avoid scape quotes.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/764
