### ISSUE TITLE
Log about "Error: Callback was already called"

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#790]
time=2024-07-01T13:06:32.021Z | lvl=FATAL | corr=n/a | trans=n/a | op=perseo | comp=perseo-fe | msg=uncaughtException: Callback was already called. Error: Callback was already called., at /opt/perseo-fe/node_modules/async/dist/async.js:969:32, at /opt/perseo-fe/node_modules/async/dist/async.js:3888:13, at Object.doIt (/opt/perseo-fe/lib/models/updateAction.js:538:16), at /opt/perseo-fe/lib/models/actions.js:119:42, at /opt/perseo-fe/node_modules/async/dist/async.js:3883:24, at replenish (/opt/perseo-fe/node_modules/async/dist/async.js:1014:17), at /opt/perseo-fe/node_modules/async/dist/async.js:1019:9, at eachOfLimit (/opt/perseo-fe/node_modules/async/dist/async.js:1044:24), at /opt/perseo-fe/node_modules/async/dist/async.js:1049:16, at _parallel (/opt/perseo-fe/node_modules/async/dist/async.js:3882:5)

This happens after error searching for a trust sin trustConf file.

**Comment by fgalan** [comment]
Fixed in PR https://github.com/telefonicaid/perseo-fe/pull/789
