### ISSUE TITLE
update rule with entity id or type expanded to non string values

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#791]
Are causing BadRequest in CB.

time=2024-07-19T08:50:45.787Z | lvl=DEBUG | corr=7a94cadb-1294-4fc1-813c-5f03c2896b16; cbnotif=1; node=O9xNsQRkJ8; perseocep=1 | trans=32c3c5b7-cbbf-43c7-8c07-2f1f0a49dbfb | op=/actions/do | path=/actions/do | comp=perseo-fe | srv=smartcity | subsrv=/ | msg=entity to update: {"actionType":"append","entities":[{"abnormal":{"value":7,"type":"Number"},"id":"thing:disp1_mirror","type":62}]}

Comes from: 
https://github.com/telefonicaid/perseo-fe/issues/746

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/792
