### ISSUE TITLE
log exception: Collection entities does not exist. Currently in strict mode.

### ISSUE THREAD

**Issue by AlvaroVega** [telefonicaid/perseo-fe#793]
time=2024-07-01T12:45:05.407Z | lvl=ERROR | corr=n/a | trans=n/a | op=checkNonSignal | comp=perseo-fe | srv=SSSS | subsrv=/ssss | msg= Collection entities does not exist. Currently in strict mode.

produced by

https://github.com/telefonicaid/perseo-fe/blob/0016fe49d900413a9ee27a6c340842ce94a1c78f/lib/models/entitiesStore.js#L154

**Comment by AlvaroVega** [comment]
related https://github.com/telefonicaid/perseo-fe/issues/422

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/794
