### ISSUE TITLE
Log Warning: `DeprecationWarning: collection.save is deprecated`

### ISSUE THREAD

**Issue by mapedraza** [telefonicaid/perseo-fe#806]
After updating to latest version, now we are getting the following log entry:

```
(node:1) DeprecationWarning: collection.save is deprecated. Use insertOne, insertMany, updateOne, or updateMany instead.
``` 

It is probably related with mongo operations. Consider MongoDB version support.

**Comment by mapedraza** [comment]
Probably comes from:

https://github.com/telefonicaid/perseo-fe/blob/1cf840d7f382a750b5c5fb40bac3ca6a6b47ef57/lib/models/rulesStore.js#L168-L185

**Comment by fgalan** [comment]
Fixed by PR https://github.com/telefonicaid/perseo-fe/pull/807
