### ISSUE TITLE
PERSEO_CORE_URL set in Dockerfile

### ISSUE THREAD

**Issue by pdacostaporto** [telefonicaid/perseo-fe#810]
PERSEO_CORE_URL is set in the [Dockerfile](https://github.com/telefonicaid/perseo-fe/blob/master/docker/Dockerfile#L227). This overwrites the value of `config.perseoCore` from `config.js` with a placeholder value (`http://corehost:8080`) when running a container.

PERSEO_CORE_URL should not be set in the Dockerfile. 

If you want to use `config.perseoCore` from `config.js` inside a container, the current workaround is to unset PERSEO_CORE_URL or reset it empty.

**Comment by AlvaroVega** [comment]
Typically, in a docker-compose.yml , you can set PERSEO_CORE_URL in environment section:

``` 
environment:
 - PERSEO_CORE_URL=http://iperseo-core-host:8080
 ```

**Comment by pdacostaporto** [comment]
> Typically, in a docker-compose.yml , you can set PERSEO_CORE_URL in environment section:
> 
> ```
> environment:
>  - PERSEO_CORE_URL=http://iperseo-core-host:8080
> ```

That's not an option. I need to use the value on `config.js`.

The workaround in docker-compose would be to set PERSEO_CORE_URL empty. Also works for k8s.

**Comment by AlvaroVega** [comment]
Maybe you can contribute with whatever you need in a environment variable and adding it  to: https://github.com/telefonicasc/VentanillaUnicaSC/issues/244#issuecomment-2446215169

**Comment by pdacostaporto** [comment]
Why not remove it from the Dockerfile? Looks like it's just setting a placeholder value. I don't see what's the point of setting it there.

**Comment by fgalan** [comment]
PR https://github.com/telefonicaid/perseo-fe/pull/811, already merged

@pdacostaporto can this issue be closed?
